package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyAboutBundle extends java.util.ListResourceBundle
{
  static final Object[][] contents =
  {
    //Changing tags in the following block will
    //break the parsing of the related file
    //{{Start Automatic Code Generation Block
    {"TyAbout_title", "Tymeac"},
    //}}End Automatic Code Generation Block
    {"TyAbout_dialog", "Dialog"},
    {"OK", "OK"},
    {"CoopSoft", " CoopSoft.com"},
    {"TyVersion", "Tymeac™ for the Java Platform, Version 6.4"},
    {"copyright", "   Copyright © 1998 - 2013 Cooperative Software Systems, Inc."},
    {"TyD", "TyD.class"},
    {"look", "com/tymeac/client/jframe/help/images/cooplogo.gif"},
  };
  public Object[][] getContents()
  {
    return contents;
  }
}
