package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2011 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyAltSvrBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyAltSvr_title", "Tymeac Alter Server Options"},
		
		{"MonLabel_text", "Monitor interval in seconds"},
		{"MonLabel_toolTipText", ""},
		{"monText_text", ""},
		{"monText_toolTipText", "60 recomended"},
		{"actText_text", ""},
		{"actText_toolTipText", "Minutes, not seconds"},
		{"ActLabel_text", "Inactivation time in minutes"},
		{"ActLabel_toolTipText", ""},
		
		{"ImportButton_text", "Import"},
		{"ImportButton_actionCommand", "Import"},
		{"ImportButton_toolTipText", "Import existing data"},
		
		{"AlterButton_text", "Alter"},
		{"AlterButton_actionCommand", "Alter"},
		{"AlterButton_toolTipText", "Update to server"},
		{"SysExit_text", "   System.exit(0) at Shut Down"},
		{"SysExit_actionCommand", "   System.exit(0) at Shut Down"},
		{"SysExit_toolTipText", ""},
		
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"th_putOut", "TyAltSvr.html"},
		
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
