package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyFuncMaintBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyFuncMaint_title", "Tymeac Function Maintenance"},
		{"FunctionText_text", ""},
		{"FunctionText_toolTipText", "Enter a Tymeac Function Name"},
		{"ImportButton_text", "Import"},
		{"ImportButton_actionCommand", "Import"},
		{"ImportButton_toolTipText", "Load an existing Function"},
		{"DeleteButton_text", "Delete"},
		{"DeleteButton_actionCommand", "Delete"},
		{"DeleteButton_toolTipText", "Delete this Function"},
		{"AddButton_text", "Add"},
		{"AddButton_actionCommand", "Add"},
		{"AddButton_toolTipText", "Add this Queue to List"},
		{"RemoveButton_text", "Remove"},
		{"RemoveButton_actionCommand", "Remove"},
		{"RemoveButton_toolTipText", "Remove Selected Queue from List"},
		{"FinishButton_text", "Finish"},
		{"FinishButton_actionCommand", "Finish"},
		{"FinishButton_toolTipText", "Add/Update this Function"},
		{"FunctionLabel_text", "Function Name"},
		{"FunctionLabel_toolTipText", ""},
		{"OALabel_text", "Output Agent Queue (optional)"},
		{"OALabel_toolTipText", ""},
		{"OAText_text", ""},
		{"OAText_toolTipText", ""},
		{"AddLabel_text", "Queue Name to Add"},
		{"AddLabel_toolTipText", ""},
		{"AddText_text", ""},
		{"AddText_toolTipText", ""},
		{"ListLabel_text", "Queue List"},
		{"ListLabel_toolTipText", ""},
		{"ListScrollPane_toolTipText", "List of Queues for this Function"},
		{"TheList_toolTipText", ""},
		{"Msg_text", " Enter a Function Name"},
		{"Msg_toolTipText", ""},
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		{"OpenCfgFile_title", "Open"},
		{"OpenCfgFile_directory", ""},
		{"OpenCfgFile_file", "tymeac.xml"},
		//}}End Automatic Code Generation Block
		{"Msg_text_1", "Configuration file error"},
		{"Msg_text_2", "Error fetching dir and filename"},
		{"Msg_text_3", "Error reading Cfg File"},
		{"th_putOut", "TyFuncMaint.html"},
		{"Msg_text_4", "Enter a Queue to Add"},
		{"Msg_text_5", " Basic DataBase error"},
		{"Msg_text_6", " Configuration file error"},
		{"Msg_text_7", " No queue name entered"},
		{"Msg_text_8", " Queue does not exist"},
		{"Msg_text_9", " SQL error"},
		{"Msg_text_10", " DataBase Exception"},
		{"Msg_text_11", " Queue is an Output Agent Queue"},
		{"AddText_text_1", ""},
		{"Msg_text_12", " OK"},
		{"Msg_text_13", " OK"},
		{"Msg_text_14", " OK"},
		{"Msg_text_15", " Enter a Function name to Import"},
		{"case_0__Msg_text", " OK"},
		{"Msg_text_16", " Configuration file error"},
		{"Msg_text_17", " Function does not exist"},
		{"Msg_text_18", " Basic DataBase error"},
		{"Msg_text_19", " Enter a Function name to Delete"},
		{"Msg_text_20", " Function \'"},
		{"deleted", "\' deleted"},
		{"FunctionText_text_1", ""},
		{"OAText_text_1", ""},
		{"Msg_text_21", " Configuration file error"},
		{"Msg_text_22", " Function does not exist"},
		{"Msg_text_23", " Basic DataBase error"},
		{"Msg_text_24", " List DataBase error"},
		{"Msg_text_25", " List DataBase exception"},
		{"Msg_text_26", " Enter a Function name to Add"},
		{"case_0__Msg_text_1", " OK"},
		{"Msg_text_27", " Configuration file error"},
		{"Msg_text_28", " Function does not exist"},
		{"Msg_text_29", " Basic DataBase error"},
		{"Msg_text_30", " There are no Queues for this Function"},
		{"Msg_text_31", " List DataBase error"},
		{"Msg_text_32", " DataBase error on Insert"},
		{"Msg_text_33", " This Function was not read for Update"},
		{"Msg_text_34", " Output Agent Queue does not exist"},
		{"Msg_text_35", " Entered Ouput Agent is not an Output Agent Queue"},
		{"Msg_text_36", " Function already exists"},
		{"Msg_text_37", " At least one Queue does not exist"},
		{"Msg_text_38", " At least one Queue is not a normal Queue"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
