package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyFuncDataBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyFuncData_title", "Tymeac Generic Function Name"},
		{"FuncText_text", ""},
		{"FuncText_toolTipText", "Partial or full name"},
		{"FuncLabel_text", "Function Name"},
		{"FuncLabel_toolTipText", ""},
		{"RefreshButton_text", "Refresh"},
		{"RefreshButton_actionCommand", "Refresh"},
		{"RefreshButton_toolTipText", "Refresh the display"},
		{"ListLabel_text", "(used)  -     Name"},
		{"ListLabel_toolTipText", ""},
		{"Msg_text", " Enter Partial / Full Function Name"},
		{"Msg_toolTipText", ""},
		{"ListScrollPane_toolTipText", ""},
		{"List_toolTipText", ""},
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"th_putOut", "TyFuncData.html"},
		{"case_0__Msg_text", " Connection failure"},
		{"case_1__Msg_text", " Tymeac shutting down"},
		{"case_2__Msg_text", " Invalid Function Name"},
		{"case_3__Msg_text", " Refresh or enter a new Function name"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
