package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyMenuBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyMenu_title", "Tymeac Process Section Menu"},
		{"TyVButton_text", "Variables"},
		{"TyVButton_actionCommand", "TyVaribles"},
		{"TyVButton_toolTipText", ""},
		{"TyVLabel_text", "Start up Variables"},
		{"TyVLabel_toolTipText", ""},
		{"DBMSLabel_text", "<-- DBMS Maintenance Section -->"},
		{"DBMSLabel_toolTipText", ""},
		{"UserLabel_text", "<--User Class Maintenance Section -->"},
		{"UserLabel_toolTipText", ""},
		{"UserQueLabel_text", "User Queue Maint"},
		{"UserQueLabel_toolTipText", ""},
		{"UserFuncLabel_text", "User Func Maint"},
		{"UserFuncLabel_toolTipText", ""},
		{"TyUserVarLabel_text", "User Vari\'s Maint"},
		{"TyUserVarLabel_toolTipText", ""},
		{"TyUserQueButton_text", "User Queues"},
		{"TyUserQueButton_actionCommand", "TyQueMaint"},
		{"TyUserQueButton_toolTipText", "User Queue Class Maintenance"},
		{"TyUserFuncButton_text", "User Func"},
		{"TyUserFuncButton_actionCommand", "TyQueMaint"},
		{"TyUserFuncButton_toolTipText", "User Functions Class Maintenance"},
		{"TyUserVarButton_text", "User Var"},
		{"TyUserVarButton_actionCommand", "TyQueMaint"},
		{"TyUserVarButton_toolTipText", "User Variables Class Maintenance"},
		{"TyQueThdButton_text", "Que Threads"},
		{"TyQueThdButton_actionCommand", "TyQueThd"},
		{"TyQueThdButton_toolTipText", "Queue Threads Display"},
		{"TyWlDataButton_text", "Wait Lists"},
		{"TyWlDataButton_actionCommand", "TyWlData"},
		{"TyWlDataButton_toolTipText", "Display a Queue\'s Wait Lists"},
		{"TyStalledButton_text", "Stalled"},
		{"TyStalledButton_actionCommand", "TyStalled"},
		{"TyStalledButton_toolTipText", "Stalled Async Requests"},
		{"TyQueDataButton3_text", "Queue Data"},
		{"TyQueDataButton3_actionCommand", "TyQueData"},
		{"TyQueDataButton3_toolTipText", "Modify a live Queue\'s data"},
		{"TyShutdownButton_text", "Shut Down"},
		{"TyShutdownButton_actionCommand", "TyShutdown"},
		{"TyShutdownButton_toolTipText", "Shut Down the Tymeac Server"},
		{"TyReqStatusButton_text", "Req Status"},
		{"TyReqStatusButton_actionCommand", "TyReqStatus"},
		{"TyReqStatusButton_toolTipText", "Status of an Async Request"},
		{"TyFuncDataButton_text", "Func Data"},
		{"TyFuncDataButton_actionCommand", "TyFuncData"},
		{"TyFuncDataButton_toolTipText", "Display Function usage"},
		{"TyStatsButton_text", "Stats"},
		{"TyStatsButton_actionCommand", "TyStats"},
		{"TyStatsButton_toolTipText", "Write Tymeac System Statistics"},
		{"TyOverallButton_text", "Overall"},
		{"TyOverallButton_actionCommand", "TyOverall"},
		{"TyOverallButton_toolTipText", "Display overall system usage"},
		{"TyNewCopyButton_text", "New Copy"},
		{"TyNewCopyButton_actionCommand", "TyNewCopy"},
		{"TyNewCopyButton_toolTipText", "get a new copy of a Processing Application Class"},
		{"TyQueMaintButton_text", "Que Maint"},
		{"TyQueMaintButton_actionCommand", "TyQueMaint"},
		{"TyQueMaintButton_toolTipText", "Queue DBMS Maintenance"},
		{"TyFuncMaintButton_text", "Func Maint"},
		{"TyFuncMaintButton_actionCommand", "TyFuncMaint"},
		{"TyFuncMaintButton_toolTipText", "Function DBMS Maintenance"},
		{"TyCfgButton_text", "Config"},
		{"TyCfgButton_actionCommand", "TyCfg"},
		{"TyCfgButton_toolTipText", "Configuration File Maintenance"},
		{"TyQueThdLabel_text", "Queue Threads"},
		{"TyQueThdLabel_toolTipText", ""},
		{"TyWlDataLabel_text", "Queue Wait Lists"},
		{"TyWlDataLabel_toolTipText", ""},
		{"TyStalledLabel_text", "Stalled Requests"},
		{"TyStalledLabel_toolTipText", ""},
		{"TyQueDataLabel_text", "Modify Live Queue"},
		{"TyQueDataLabel_toolTipText", ""},
		{"TyShutdownLabel_text", "Shut Down Tymeac"},
		{"TyShutdownLabel_toolTipText", ""},
		{"TyReqStatusLabel_text", "Async Req Status"},
		{"TyReqStatusLabel_toolTipText", ""},
		{"TyFuncDataLabel_text", "Live Function Data"},
		{"TyFuncDataLabel_toolTipText", ""},
		{"TyStatsLabel_text", "Write Statistics"},
		{"TyStatsLabel_toolTipText", ""},
		{"TyOverallLabel_text", "Overall Processing"},
		{"TyOverallLabel_toolTipText", ""},
		{"TyNewCopyLabel_text", "New Appl. Class"},
		{"TyNewCopyLabel_toolTipText", ""},
		{"TyQueMaintLabel_text", "Queue DBMS Maint"},
		{"TyQueMaintLabel_toolTipText", ""},
		{"TyFuncMaintLabel_text", "Func. DBMS Maint"},
		{"TyFuncMaintLabel_toolTipText", ""},
		{"TyCfgLabel_text", "Cfg File Maint"},
		{"TyCfgLabel_toolTipText", ""},
    
    {"TyNewRTNotifyLabel_text", "Run Time Notification"},
    {"TyNewRTNotifyLabel_toolTipText", ""},
    {"TyNewRTNotifyButton_text", "New Notification"},
    {"TyNewRTNotifyButton_actionCommand", "TyNewRTNotify"},
    {"TyNewRTNotifyButton_toolTipText", "alter run time notification"},
    
    {"TyNewRTLogLabel_text", "Run Time Logging"},
    {"TyNewRTLogLabel_toolTipText", ""},
    {"TyNewRTLogButton_text", "New Logging"},
    {"TyNewRTLogButton_actionCommand", "TyNewRTLog"},
    {"TyNewRTLogButton_toolTipText", "alter run time logging"},
    
    {"TyNewRTStatsLabel_text", "Run Time Stats"},
    {"TyNewRTStatsLabel_toolTipText", ""},
    {"TyNewRTStatsButton_text", "New Stats"},
    {"TyNewRTStatsButton_actionCommand", "TyNewRTStats"},
    {"TyNewRTStatsButton_toolTipText", "alter run time statistics"},
    
    {"TyAltSvrLabel_text", "Alter Server Options"},
    {"TyAltSvrLabel_toolTipText", ""},
    {"TyAltSvrButton_text", "Alter Opts"},
    {"TyAltSvrButton_actionCommand", "TyAltSvr"},
    {"TyAltSvrButton_toolTipText", "alter server options"},
    
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"TyQueMaintButton_text_1", "Unsupported"},
		{"TyFuncMaintButton_text_1", "Unsupported"},
		{"TyCfgButton_text_1", "Unsupported"},
		{"th_putOut", "TyMenu.html"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
