package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

import java.awt.*;
import javax.swing.*;
import com.tymeac.base.*;
/**
 * The New Copy display frame.
 */
public class TyNewCopy extends javax.swing.JFrame
{
  private static final long serialVersionUID = 1L;

  // Used by addNotify
  boolean frameSizeAdjusted = false;

  //{{DECLARE_CONTROLS
	javax.swing.JTextField QueText = new javax.swing.JTextField();
	javax.swing.JTextField ClassText = new javax.swing.JTextField();
	javax.swing.JLabel QueLabel = new javax.swing.JLabel();
	javax.swing.JLabel ClassLabel = new javax.swing.JLabel();
	javax.swing.JLabel Msg = new javax.swing.JLabel();
	javax.swing.JButton LoadButton = new javax.swing.JButton();
	javax.swing.JMenuBar JMenuBar1 = new javax.swing.JMenuBar();
	javax.swing.JMenu fileMenu = new javax.swing.JMenu();
	javax.swing.JMenuItem exitItem = new javax.swing.JMenuItem();
	javax.swing.JSeparator JSeparator1 = new javax.swing.JSeparator();
	javax.swing.JMenu helpMenu = new javax.swing.JMenu();
	javax.swing.JMenuItem Help = new javax.swing.JMenuItem();
	javax.swing.JMenuItem about = new javax.swing.JMenuItem();
	//}}

  TyNewCopyBean2 TyNewCopyBean21 = null;
	TymeacInterface Ti = null;

  class SymWindow extends java.awt.event.WindowAdapter
  {
	public void windowClosing(java.awt.event.WindowEvent event)
	{
	  Object object = event.getSource();
	  if (object == TyNewCopy.this)
		TyNewCopy_windowClosing(event);
	}
  }

  class SymAction implements java.awt.event.ActionListener
  {
	public void actionPerformed(java.awt.event.ActionEvent event)
	{ 
	  Object object = event.getSource();
	  if (object == exitItem)
		exitItem_actionPerformed(event);
	  else if (object == Help)
		Help_actionPerformed(event);
	  else  if (object == about)
		about_actionPerformed(event);
	  else if (object == LoadButton)
		LoadButton_actionPerformed(event);		  
	  
	}
  }

	static java.util.ResourceBundle tyNewCopyBundle = java.util.ResourceBundle.getBundle("com.tymeac.client.jframe.TyNewCopyBundle");
  public TyNewCopy()
  {
	// This code is automatically generated by Visual Cafe when you add
	// components to the visual environment. It instantiates and initializes
	// the components. To modify the code, only use code syntax that matches
	// what Visual Cafe can generate, or Visual Cafe may be unable to back
	// parse your Java file into its visual environment.
	//{{INIT_CONTROLS
	setJMenuBar(JMenuBar1);
	setTitle(tyNewCopyBundle.getString("TyNewCopy_title"));
	setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
	getContentPane().setLayout(null);
	setSize(426,240);
	setVisible(false);
		QueText.setText(tyNewCopyBundle.getString("QueText_text"));
	//$$ JMenuBar1.move(168,312);
	fileMenu.setText(tyNewCopyBundle.getString("fileMenu_text"));
	fileMenu.setActionCommand(tyNewCopyBundle.getString("fileMenu_actionCommand"));
		fileMenu.setToolTipText(tyNewCopyBundle.getString("fileMenu_toolTipText").length() != 0 ? tyNewCopyBundle.getString("fileMenu_toolTipText") : null);
	fileMenu.setMnemonic((int)'F');
	JMenuBar1.add(fileMenu);
	
	fileMenu.add(JSeparator1);
	
	exitItem.setText(tyNewCopyBundle.getString("exitItem_text"));
	exitItem.setActionCommand(tyNewCopyBundle.getString("exitItem_actionCommand"));
		exitItem.setToolTipText(tyNewCopyBundle.getString("exitItem_toolTipText").length() != 0 ? tyNewCopyBundle.getString("exitItem_toolTipText") : null);
	exitItem.setMnemonic((int)'X');
	fileMenu.add(exitItem);
		JSeparator1.setToolTipText(tyNewCopyBundle.getString("JSeparator1_toolTipText").length() != 0 ? tyNewCopyBundle.getString("JSeparator1_toolTipText") : null);
	
	helpMenu.setText(tyNewCopyBundle.getString("helpMenu_text"));
	helpMenu.setActionCommand(tyNewCopyBundle.getString("helpMenu_actionCommand"));
		helpMenu.setToolTipText(tyNewCopyBundle.getString("helpMenu_toolTipText").length() != 0 ? tyNewCopyBundle.getString("helpMenu_toolTipText") : null);
	helpMenu.setMnemonic((int)'H');
	JMenuBar1.add(helpMenu);
	
	fileMenu.add(JSeparator1);
	   
	Help.setText(tyNewCopyBundle.getString("Help_text"));
	Help.setActionCommand(tyNewCopyBundle.getString("Help_actionCommand"));
		Help.setToolTipText(tyNewCopyBundle.getString("Help_toolTipText").length() != 0 ? tyNewCopyBundle.getString("Help_toolTipText") : null);
	Help.setMnemonic((int)'D');
	helpMenu.add(Help);
	
	fileMenu.add(JSeparator1);
	
	about.setText(tyNewCopyBundle.getString("about_text"));
	about.setActionCommand(tyNewCopyBundle.getString("about_actionCommand"));
		about.setToolTipText(tyNewCopyBundle.getString("about_toolTipText").length() != 0 ? tyNewCopyBundle.getString("about_toolTipText") : null);
	about.setMnemonic((int)'A');
	helpMenu.add(about); 
	//$$ etchedBorder1.move(192,312);
	QueText.setToolTipText(tyNewCopyBundle.getString("QueText_toolTipText").length() != 0 ? tyNewCopyBundle.getString("QueText_toolTipText") : null);
	getContentPane().add(QueText);
	QueText.setBounds(24,24,300,30);
		ClassText.setText(tyNewCopyBundle.getString("ClassText_text"));
	ClassText.setToolTipText(tyNewCopyBundle.getString("ClassText_toolTipText").length() != 0 ? tyNewCopyBundle.getString("ClassText_toolTipText") : null);
	getContentPane().add(ClassText);
	ClassText.setBounds(24,96,384,30);
	QueLabel.setText(tyNewCopyBundle.getString("QueLabel_text"));
		QueLabel.setToolTipText(tyNewCopyBundle.getString("QueLabel_toolTipText").length() != 0 ? tyNewCopyBundle.getString("QueLabel_toolTipText") : null);
	getContentPane().add(QueLabel);
	QueLabel.setBounds(24,55,123,22);
	ClassLabel.setText(tyNewCopyBundle.getString("ClassLabel_text"));
		ClassLabel.setToolTipText(tyNewCopyBundle.getString("ClassLabel_toolTipText").length() != 0 ? tyNewCopyBundle.getString("ClassLabel_toolTipText") : null);
	getContentPane().add(ClassLabel);
	ClassLabel.setBounds(24,125,197,19);
	Msg.setText(tyNewCopyBundle.getString("Msg_text"));
		Msg.setToolTipText(tyNewCopyBundle.getString("Msg_toolTipText").length() != 0 ? tyNewCopyBundle.getString("Msg_toolTipText") : null);
	getContentPane().add(Msg);
	Msg.setForeground(new java.awt.Color(128,0,0));
	Msg.setBounds(20,200,386,30);
	LoadButton.setText(tyNewCopyBundle.getString("LoadButton_text"));
	LoadButton.setActionCommand(tyNewCopyBundle.getString("LoadButton_actionCommand"));
		LoadButton.setToolTipText(tyNewCopyBundle.getString("LoadButton_toolTipText").length() != 0 ? tyNewCopyBundle.getString("LoadButton_toolTipText") : null);
	getContentPane().add(LoadButton);
	LoadButton.setBounds(348,24,63,34);
		JMenuBar1.setToolTipText(tyNewCopyBundle.getString("JMenuBar1_toolTipText").length() != 0 ? tyNewCopyBundle.getString("JMenuBar1_toolTipText") : null);

	//}}

	Msg.setBorder(new javax.swing.border.EtchedBorder());
	

	//{{INIT_MENUS
	//}}

	//{{REGISTER_LISTENERS
	SymWindow aSymWindow = new SymWindow();
	this.addWindowListener(aSymWindow);
	
	SymAction lSymAction = new SymAction();
	exitItem.addActionListener(lSymAction);
	Help.addActionListener(lSymAction);
	about.addActionListener(lSymAction);
	LoadButton.addActionListener(lSymAction);
	//}}
  }
 public TyNewCopy(TymeacInterface TyI)
    {
		this();
    Ti = TyI;

    try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (Exception e) { 
        }
 }
	/**
	 * Creates a new instance of JFrame1 with the given title.
	 * @param sTitle the title for the new frame.
	 */
  public TyNewCopy(String sTitle)
  {
	this();
	setTitle(sTitle);
  }
   void about_actionPerformed(java.awt.event.ActionEvent event)
  {
	// to do: code goes here.
	   
	about_actionPerformed_Interaction1(event);
  }
  void about_actionPerformed_Interaction1(java.awt.event.ActionEvent event) { 
  
	try {
	  // TymeacAbout Create with owner and show as modal
	  {
		TyAbout TyAbout1 = new TyAbout(this);
		TyAbout1.setModal(true);
		TyAbout1.setVisible(true);
	  }
	} catch (Exception e) {
	}
  }
	/**
	 * Notifies this component that it has been added to a container
	 * This method should be called by <code>Container.add</code>, and 
	 * not by user code directly.
	 * Overridden here to adjust the size of the frame if needed.
	 * @see java.awt.Container#removeNotify
	 */
  public void addNotify()
  {
	// Record the size of the window prior to calling parents addNotify.
	Dimension size = getSize();
	
	super.addNotify();
	
	if (frameSizeAdjusted)
	  return;
	frameSizeAdjusted = true;
	
	// Adjust size of frame according to the insets and menu bar
	javax.swing.JMenuBar menuBar = getRootPane().getJMenuBar();
	int menuBarHeight = 0;
	if (menuBar != null)
		menuBarHeight = menuBar.getPreferredSize().height;
	Insets insets = getInsets();
	setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height + menuBarHeight);
  }
  //{{DECLARE_MENUS
	//}}

  void exitApplication()
  {    
	this.setVisible(false);    // hide the Frame
	this.dispose();            // free the system resources
	 if (Ti == null) {
      System.exit(0);            // close the application 
   }
  }
  void exitItem_actionPerformed(java.awt.event.ActionEvent event)
  {
	// to do: code goes here.
	   
	exitItem_actionPerformed_Interaction1(event);
  }
  void exitItem_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
	try {
	  this.exitApplication();
	} catch (Exception e) {
	}
  }
  void Help_actionPerformed(java.awt.event.ActionEvent event)
  {
	// to do: code goes here.
	   
	Help_actionPerformed_Interaction1(event);
  }
  void Help_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
	
	TyHelp th = new TyHelp();

	th.putOut(tyNewCopyBundle.getString("th_putOut"));
	
  }
  void LoadButton_actionPerformed(java.awt.event.ActionEvent event)
  {
	// to do: code goes here.
	   
	LoadButton_actionPerformed_Interaction1(event);
  }
  void LoadButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
  {
	try {
	  // text field to string
	  String aData = QueText.getText();

	  // When no data
	  if  ((aData == null) ||
		 	   (aData.length() < 1)) {

		  	// say so
		  	Msg.setText(tyNewCopyBundle.getString("Msg_text_1"));

			  // done
			  return;

	  } // endif
	
	  // When no obj 
	  if  (TyNewCopyBean21 == null) {

				// When internal
		    if  (Ti != null) {

    		     // get the obj
        		 TyNewCopyBean21 = new TyNewCopyBean2(Ti);
    		}
    		else {
        		// get the obj
        		TyNewCopyBean21 = new TyNewCopyBean2();

    		} // endif
	  } // endif

	  // do function
	  TyNewCopyBean21.loadButton(QueText, ClassText);

	  // result
	  switch (TyNewCopyBean21.getLoadResult()) {

		  case 0: Msg.setText(tyNewCopyBundle.getString("case_0__Msg_text"));
				  return;                   
			
		  case -1: Msg.setText(tyNewCopyBundle.getString("case__1__Msg_text")); 
				   return;
		
		  case 1: Msg.setText(tyNewCopyBundle.getString("case_1__Msg_text")); 
				  return;         
				  
		  case 2: Msg.setText(tyNewCopyBundle.getString("case_2__Msg_text")); 
				  return; 
		
		  case 3: Msg.setText(tyNewCopyBundle.getString("case_3__Msg_text")); 
				  return;
				  
		  case 4: Msg.setText(tyNewCopyBundle.getString("case_4__Msg_text")); 
				  return;

			case 5: Msg.setText(tyNewCopyBundle.getString("case_5__Msg_text")); 
				  return;

			case 6: Msg.setText(tyNewCopyBundle.getString("case_6__Msg_text")); 
				  return;

			case 7: Msg.setText(tyNewCopyBundle.getString("case_7__Msg_text")); 
				  return;

			case 8: Msg.setText(tyNewCopyBundle.getString("case_8__Msg_text")); 
				  return;

			case 9: Msg.setText(tyNewCopyBundle.getString("case_9__Msg_text")); 
				  return;

			case 10: Msg.setText(tyNewCopyBundle.getString("case_10__Msg_text")); 
				  return;			
								
	} // end-switch

	} catch (java.lang.Exception e) {
	}
  }
  /**
   * The entry point for this application.
   * Sets the Look and Feel to the System Look and Feel.
   * Creates a new JFrame1 and makes it visible.
   */
  static public void main(String args[])
  {
	try {
		// Add the following code if you want the Look and Feel
		// to be set to the Look and Feel of the native system.
		
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} 
		catch (Exception e) { 
		}
		

	  //Create a new instance of our application's frame, and make it visible.
	  (new TyNewCopy()).setVisible(true);
	} 
	catch (Throwable t) {
	  t.printStackTrace();
	  //Ensure the application exits with an error condition.
	  System.exit(1);
	}
  }
  void TyNewCopy_windowClosing(java.awt.event.WindowEvent event)
  {
	// to do: code goes here.
	   
	TyNewCopy_windowClosing_Interaction1(event);
  }
  void TyNewCopy_windowClosing_Interaction1(java.awt.event.WindowEvent event) {
	try {
	  this.exitApplication();
	} catch (Exception e) {
	}
  }
}
