package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyNewCopyBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyNewCopy_title", "Tymeac -- New Copy of Application Class"},
		{"QueText_text", ""},
		{"QueText_toolTipText", "Enter a Queue Name"},
		{"ClassText_text", ""},
		{"ClassText_toolTipText", "(optional) new Class Name"},
		{"QueLabel_text", "  Queue Name"},
		{"QueLabel_toolTipText", ""},
		{"ClassLabel_text", "  (new) Appl. Class Name::URL"},
		{"ClassLabel_toolTipText", ""},
		{"Msg_text", " Enter Queue Name"},
		{"Msg_toolTipText", ""},
		{"LoadButton_text", "Load"},
		{"LoadButton_actionCommand", "Load"},
		{"LoadButton_toolTipText", ""},
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"th_putOut", "TyNewCopy.html"},
		{"Msg_text_1", " Enter a Queue name"},
		{"case_0__Msg_text", " Successful"},
		{"case__1__Msg_text", " Connection error"},
		{"case_1__Msg_text", " Enter a New Class Name"},
		{"case_2__Msg_text", " New Class load error"},
		{"case_3__Msg_text", " Queue Name Invalid"},
		{"case_4__Msg_text", " Threads are busy, try later"},
		{"case_5__Msg_text", " Enter a Queue Name"},
		{"case_6__Msg_text", " Original load was not with a URLClassLoader"},
		{"case_7__Msg_text", " Re-load of original class, load error"},
		{"case_8__Msg_text", " Invalid Class::URL format"},
		{"case_9__Msg_text", " Invalid URL format"},
		{"case_10__Msg_text", " New class name same as original"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
