package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyOverallBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyOverall_title", "Tymeac Overall Status"},
		{"ListLabel_text", "Queues with Attendant Threads"},
		{"ListLabel_toolTipText", ""},
		{"TopButton_text", "Refresh Top"},
		{"TopButton_actionCommand", "Refresh Top"},
		{"TopButton_toolTipText", "Use to refresh the left list"},
		{"BottomButton_text", "Refresh Both"},
		{"BottomButton_actionCommand", "Refresh Both"},
		{"BottomButton_toolTipText", "use to refresh both lists"},
		{"Msg_text", " Press one of the buttons"},
		{"Msg_toolTipText", ""},
		{"TopList_toolTipText", ""},
		{"JScrollPane1_toolTipText", ""},
		{"BottomList_toolTipText", ""},
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"th_putOut", "TyOverall.html"},
		{"case_0__Msg_text", " Connection failure."},
		{"case_1__Msg_text", " Ok"},
		{"case_0__Msg_text_1", " Connection failure."},
		{"case_1__Msg_text_1", " Ok"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
