package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2013 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

import java.awt.*;
import javax.swing.*;
import com.tymeac.base.*;

/**
 * The Queue Threads display frame.
 */
public class TyQueThd extends javax.swing.JFrame
{  
  private static final long serialVersionUID = 1L;

  // Used by addNotify
  boolean frameSizeAdjusted = false;

  //{{DECLARE_CONTROLS
	javax.swing.JTextField QueText = new javax.swing.JTextField();
	javax.swing.JLabel QueLabel = new javax.swing.JLabel();
	javax.swing.JButton RefreshButton = new javax.swing.JButton();
	javax.swing.JButton DisableButton = new javax.swing.JButton();
	javax.swing.JButton EnableButton = new javax.swing.JButton();
	
	javax.swing.JButton EnableSpecificButton = new javax.swing.JButton();
	
	javax.swing.JLabel Msg = new javax.swing.JLabel();
	javax.swing.JScrollPane JScrollPane1 = new javax.swing.JScrollPane();
	javax.swing.JList TheList = new javax.swing.JList();
	javax.swing.JLabel ListLabel = new javax.swing.JLabel();
	javax.swing.JMenuBar JMenuBar1 = new javax.swing.JMenuBar();
	javax.swing.JMenu fileMenu = new javax.swing.JMenu();
	javax.swing.JMenuItem exitItem = new javax.swing.JMenuItem();
	javax.swing.JSeparator JSeparator1 = new javax.swing.JSeparator();
	javax.swing.JMenu helpMenu = new javax.swing.JMenu();
	javax.swing.JMenuItem Help = new javax.swing.JMenuItem();
	javax.swing.JMenuItem about = new javax.swing.JMenuItem();
	//}}

	TyQueThdBean2 TyQueThdBean21 = null;
	TymeacInterface Ti = null;

  class SymWindow extends java.awt.event.WindowAdapter
  {
    public void windowClosing(java.awt.event.WindowEvent event)
    {
      Object object = event.getSource();
      if (object == TyQueThd.this)
        TyQueThd_windowClosing(event);
    }
  }

  class SymAction implements java.awt.event.ActionListener
  {
    public void actionPerformed(java.awt.event.ActionEvent event)
    { 
      Object object = event.getSource();
      if (object == exitItem)
        exitItem_actionPerformed(event);
      else if (object == Help)
        Help_actionPerformed(event);
      else  if (object == about)
        about_actionPerformed(event);
			else if (object == RefreshButton)
				RefreshButton_actionPerformed(event);
			else if (object == DisableButton)
				DisableButton_actionPerformed(event);
			else if (object == EnableButton)
				EnableButton_actionPerformed(event);
      else if (object == EnableSpecificButton)
        EnableSpecificButton_actionPerformed(event);   
      
    }
  }

	class SymListSelection implements javax.swing.event.ListSelectionListener
	{
		public void valueChanged(javax.swing.event.ListSelectionEvent event)
		{
			Object object = event.getSource();
			if (object == TheList)
				TheList_valueChanged(event);
		}
	}

	static java.util.ResourceBundle tyQueThdBundle = java.util.ResourceBundle.getBundle("com.tymeac.client.jframe.TyQueThdBundle");
  public TyQueThd()
  {
    // This code is automatically generated by Visual Cafe when you add
    // components to the visual environment. It instantiates and initializes
    // the components. To modify the code, only use code syntax that matches
    // what Visual Cafe can generate, or Visual Cafe may be unable to back
    // parse your Java file into its visual environment.
    //{{INIT_CONTROLS
    setJMenuBar(JMenuBar1);
    setTitle(tyQueThdBundle.getString("TyQueThd_title"));
    setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    getContentPane().setLayout(null);
    setSize(520,375);
		setVisible(false);
		QueText.setText(tyQueThdBundle.getString("QueText_text"));
    //$$ JMenuBar1.move(132,372);
    fileMenu.setText(tyQueThdBundle.getString("fileMenu_text"));
    fileMenu.setActionCommand(tyQueThdBundle.getString("fileMenu_actionCommand"));
		fileMenu.setToolTipText(tyQueThdBundle.getString("fileMenu_toolTipText").length() != 0 ? tyQueThdBundle.getString("fileMenu_toolTipText") : null);
    fileMenu.setMnemonic((int)'F');
    JMenuBar1.add(fileMenu);
    
    fileMenu.add(JSeparator1);
    
    exitItem.setText(tyQueThdBundle.getString("exitItem_text"));
    exitItem.setActionCommand(tyQueThdBundle.getString("exitItem_actionCommand"));
		exitItem.setToolTipText(tyQueThdBundle.getString("exitItem_toolTipText").length() != 0 ? tyQueThdBundle.getString("exitItem_toolTipText") : null);
    exitItem.setMnemonic((int)'X');
    fileMenu.add(exitItem);
		JSeparator1.setToolTipText(tyQueThdBundle.getString("JSeparator1_toolTipText").length() != 0 ? tyQueThdBundle.getString("JSeparator1_toolTipText") : null);
    
    helpMenu.setText(tyQueThdBundle.getString("helpMenu_text"));
    helpMenu.setActionCommand(tyQueThdBundle.getString("helpMenu_actionCommand"));
		helpMenu.setToolTipText(tyQueThdBundle.getString("helpMenu_toolTipText").length() != 0 ? tyQueThdBundle.getString("helpMenu_toolTipText") : null);
    helpMenu.setMnemonic((int)'H');
    JMenuBar1.add(helpMenu);
    
    fileMenu.add(JSeparator1);
       
    Help.setText(tyQueThdBundle.getString("Help_text"));
    Help.setActionCommand(tyQueThdBundle.getString("Help_actionCommand"));
		Help.setToolTipText(tyQueThdBundle.getString("Help_toolTipText").length() != 0 ? tyQueThdBundle.getString("Help_toolTipText") : null);
    Help.setMnemonic((int)'D');
    helpMenu.add(Help);
    
    fileMenu.add(JSeparator1);
    
    about.setText(tyQueThdBundle.getString("about_text"));
    about.setActionCommand(tyQueThdBundle.getString("about_actionCommand"));
		about.setToolTipText(tyQueThdBundle.getString("about_toolTipText").length() != 0 ? tyQueThdBundle.getString("about_toolTipText") : null);
    about.setMnemonic((int)'A');
    helpMenu.add(about); 
		QueText.setToolTipText(tyQueThdBundle.getString("QueText_toolTipText").length() != 0 ? tyQueThdBundle.getString("QueText_toolTipText") : null);
		getContentPane().add(QueText);
		QueText.setBounds(24,24,200,30);
		QueLabel.setText(tyQueThdBundle.getString("QueLabel_text"));
		QueLabel.setToolTipText(tyQueThdBundle.getString("QueLabel_toolTipText").length() != 0 ? tyQueThdBundle.getString("QueLabel_toolTipText") : null);
		getContentPane().add(QueLabel);
		QueLabel.setBounds(24,55,110,20);
		RefreshButton.setText(tyQueThdBundle.getString("RefreshButton_text"));
		RefreshButton.setActionCommand(tyQueThdBundle.getString("RefreshButton_actionCommand"));
		RefreshButton.setToolTipText(tyQueThdBundle.getString("RefreshButton_toolTipText").length() != 0 ? tyQueThdBundle.getString("RefreshButton_toolTipText") : null);
		getContentPane().add(RefreshButton);
		RefreshButton.setBounds(370,24,140,40);
		
		DisableButton.setText(tyQueThdBundle.getString("DisableButton_text"));
		DisableButton.setActionCommand(tyQueThdBundle.getString("DisableButton_actionCommand"));
		DisableButton.setToolTipText(tyQueThdBundle.getString("DisableButton_toolTipText").length() != 0 ? tyQueThdBundle.getString("DisableButton_toolTipText") : null);
		DisableButton.setEnabled(false);
		getContentPane().add(DisableButton);
		DisableButton.setBounds(370,121,140,40);
		
		EnableButton.setText(tyQueThdBundle.getString("EnableButton_text"));
		EnableButton.setActionCommand(tyQueThdBundle.getString("EnableButton_actionCommand"));
		EnableButton.setToolTipText(tyQueThdBundle.getString("EnableButton_toolTipText").length() != 0 ? tyQueThdBundle.getString("EnableButton_toolTipText") : null);
		EnableButton.setEnabled(false);
		getContentPane().add(EnableButton);
		EnableButton.setBounds(370,282,140,40);
		
		EnableSpecificButton.setText(tyQueThdBundle.getString("EnableSpecificButton_text"));
    EnableSpecificButton.setActionCommand(tyQueThdBundle.getString("EnableSpecificButton_actionCommand"));
    EnableSpecificButton.setToolTipText(tyQueThdBundle.getString("EnableSpecificButton_toolTipText").length() != 0 ? tyQueThdBundle.getString("EnableSpecificButton_toolTipText") : null);
    EnableSpecificButton.setEnabled(false);
    getContentPane().add(EnableSpecificButton);
    EnableSpecificButton.setBounds(370,180,140,40);		
		
		Msg.setText(tyQueThdBundle.getString("Msg_text"));
		Msg.setToolTipText(tyQueThdBundle.getString("Msg_toolTipText").length() != 0 ? tyQueThdBundle.getString("Msg_toolTipText") : null);
		getContentPane().add(Msg);
		Msg.setForeground(new java.awt.Color(128,0,0));
		Msg.setBounds(20,335,480,30);
		JScrollPane1.setOpaque(true);
		JScrollPane1.setToolTipText(tyQueThdBundle.getString("JScrollPane1_toolTipText").length() != 0 ? tyQueThdBundle.getString("JScrollPane1_toolTipText") : null);
		getContentPane().add(JScrollPane1);
		JScrollPane1.setBounds(24,120,310,204);
		TheList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		TheList.setToolTipText(tyQueThdBundle.getString("TheList_toolTipText").length() != 0 ? tyQueThdBundle.getString("TheList_toolTipText") : null);
		JScrollPane1.getViewport().add(TheList);
		TheList.setBounds(0,0,307,201);
		ListLabel.setText(tyQueThdBundle.getString("ListLabel_text"));
		ListLabel.setToolTipText(tyQueThdBundle.getString("ListLabel_toolTipText").length() != 0 ? tyQueThdBundle.getString("ListLabel_toolTipText") : null);
		getContentPane().add(ListLabel);
		ListLabel.setBounds(28,95,200,20);
		JMenuBar1.setToolTipText(tyQueThdBundle.getString("JMenuBar1_toolTipText").length() != 0 ? tyQueThdBundle.getString("JMenuBar1_toolTipText") : null);

    //}}

		Msg.setBorder(new javax.swing.border.EtchedBorder());

    //{{INIT_MENUS
    //}}

    //{{REGISTER_LISTENERS
    SymWindow aSymWindow = new SymWindow();
    this.addWindowListener(aSymWindow);
    
    SymAction lSymAction = new SymAction();
    exitItem.addActionListener(lSymAction);
    Help.addActionListener(lSymAction);
    about.addActionListener(lSymAction);
		RefreshButton.addActionListener(lSymAction);
		DisableButton.addActionListener(lSymAction);
		EnableButton.addActionListener(lSymAction);
		EnableSpecificButton.addActionListener(lSymAction);
		SymListSelection lSymListSelection = new SymListSelection();
		TheList.addListSelectionListener(lSymListSelection);
		//}}
  }
    public TyQueThd(TymeacInterface TyI)
    {
			this();
    	Ti = TyI;

    	try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (Exception e) { 
        }
    }
    /**
     * Creates a new instance of JFrame1 with the given title.
     * @param sTitle the title for the new frame.
     */
  public TyQueThd(String sTitle)
  {
    this();
    setTitle(sTitle);
  }
   void about_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    about_actionPerformed_Interaction1(event);
  }
  void about_actionPerformed_Interaction1(java.awt.event.ActionEvent event) { 
  
    try {
      // TymeacAbout Create with owner and show as modal
      {
        TyAbout TyAbout1 = new TyAbout(this);
        TyAbout1.setModal(true);
        TyAbout1.setVisible(true);
      }
    } catch (Exception e) {
    }
  }
    /**
     * Notifies this component that it has been added to a container
     * This method should be called by <code>Container.add</code>, and 
     * not by user code directly.
     * Overridden here to adjust the size of the frame if needed.
     * @see java.awt.Container#removeNotify
     */
  public void addNotify()
  {
    // Record the size of the window prior to calling parents addNotify.
    Dimension size = getSize();
    
    super.addNotify();
    
    if (frameSizeAdjusted)
      return;
    frameSizeAdjusted = true;
    
    // Adjust size of frame according to the insets and menu bar
    javax.swing.JMenuBar menuBar = getRootPane().getJMenuBar();
    int menuBarHeight = 0;
    if (menuBar != null)
        menuBarHeight = menuBar.getPreferredSize().height;
    Insets insets = getInsets();
    setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height + menuBarHeight);
  }
	void DisableButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		DisableButton_actionPerformed_Interaction1(event);
	}
	void DisableButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {        
    		// function
    		TyQueThdBean21.disableButton(QueText, (String)TheList.getSelectedValue(), TheList);
       
    		// the result of this:
    		switch (TyQueThdBean21.getDisResult()) {
                  
        		case 0: Msg.setText(tyQueThdBundle.getString("case_0__Msg_text_1"));
            	      break;                    
            
        		case 1: Msg.setText(tyQueThdBundle.getString("case_1__Msg_text_1")); 
            		     break;
                  
		        case 2: Msg.setText(tyQueThdBundle.getString("case_2__Msg_text_1")); 
    	              break;
        
      		  case 3: Msg.setText(tyQueThdBundle.getString("case_3__Msg_text_1")); 
          	        break;
        
		        case 4: Msg.setText(tyQueThdBundle.getString("case_4__Msg_text")); 
    	              break;
        
      		  case 5: Msg.setText(tyQueThdBundle.getString("case_5__Msg_text")); 
          	        break;
                            
    		} // end-switch   


		} catch (java.lang.Exception e) {
		}
	}
	void EnableButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		EnableButton_actionPerformed_Interaction1(event);
	}
	void EnableButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
    		// function
    		TyQueThdBean21.enableButton(QueText, TheList);
       
  		 // the result of this:
    		switch (TyQueThdBean21.getEnaResult()) {
                  
        		case 0: Msg.setText(tyQueThdBundle.getString("case_0__Msg_text_2"));
            	      break;                    
            
  					case 1: Msg.setText(tyQueThdBundle.getString("case_1__Msg_text_2")); 
      	    				break;
        
        		case 2: Msg.setText(tyQueThdBundle.getString("case_2__Msg_text_2")); 
          	        break;
        
	        	case 3: Msg.setText(tyQueThdBundle.getString("case_3__Msg_text_2")); 
                    break;

  	      	case 4: Msg.setText(tyQueThdBundle.getString("case_4__Msg_text_1")); 
            	      break;
                  
    		} // end-switch    

		} catch (java.lang.Exception e) {
		}
	}
	
	void EnableSpecificButton_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    EnableSpecificButton_actionPerformed_Interaction1(event);
  }
  void EnableSpecificButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
  {
    try {
        // function
        TyQueThdBean21.enableSpecificButton( QueText, 
                                            (String)TheList.getSelectedValue(), 
                                            TheList);
       
       // the result of this:
        switch (TyQueThdBean21.getEnaSpecResult()) {
                  
            case 0: Msg.setText(tyQueThdBundle.getString("case_0__Msg_text_1"));
                    break;                    
            
            case 1: Msg.setText(tyQueThdBundle.getString("case_1__Msg_text_1")); 
                     break;
                  
            case 2: Msg.setText(tyQueThdBundle.getString("case_2__Msg_text_1")); 
                    break;
        
            case 3: Msg.setText(tyQueThdBundle.getString("case_3__Msg_text_1")); 
                    break;
        
            case 4: Msg.setText(tyQueThdBundle.getString("case_4__Msg_text")); 
                    break;
        
            case 5: Msg.setText(tyQueThdBundle.getString("case_5__Msg_text")); 
                    break;
                  
        } // end-switch    

    } catch (java.lang.Exception e) {
    }
  }
  //{{DECLARE_MENUS
	//}}

  void exitApplication()
  {    
    this.setVisible(false);    // hide the Frame
    this.dispose();        // free the system resources
		if  (Ti == null) {
    		System.exit(0);  // close the application 
		} // endif    
  }
  void exitItem_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    exitItem_actionPerformed_Interaction1(event);
  }
  void exitItem_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
    try {
      this.exitApplication();
    } catch (Exception e) {
    }
  }
  void Help_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    Help_actionPerformed_Interaction1(event);
  }
  void Help_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
    
    TyHelp th = new TyHelp();

    th.putOut(tyQueThdBundle.getString("th_putOut"));
    
  }
  /**
   * The entry point for this application.
   * Sets the Look and Feel to the System Look and Feel.
   * Creates a new JFrame1 and makes it visible.
   */
  static public void main(String args[])
  {
    try {
        // Add the following code if you want the Look and Feel
        // to be set to the Look and Feel of the native system.
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (Exception e) { 
        }
        

      //Create a new instance of our application's frame, and make it visible.
      (new TyQueThd()).setVisible(true);
    } 
    catch (Throwable t) {
      t.printStackTrace();
      //Ensure the application exits with an error condition.
      System.exit(1);
    }
  }
	void RefreshButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		RefreshButton_actionPerformed_Interaction1(event);
	}
	void RefreshButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
				// must enter a name
				String que = QueText.getText();

				// When no name
				if  ((que == null) ||
						 (que.length() < 1)) {

						//
						Msg.setText(tyQueThdBundle.getString("Msg_text_1"));

						// done
						return;

				 } // endif	

			// When no obj
			if  (TyQueThdBean21 == null) {

					// When internal
          if  (Ti != null) {

              // get the obj
              TyQueThdBean21 = new TyQueThdBean2(Ti);
          }
          else {
          		 // get the obj
            	 TyQueThdBean21 = new TyQueThdBean2();

          } // endif
			} // endif
    
    	// user code end
    	TyQueThdBean21.refreshButton(QueText, TheList);
    	// user code begin {2}
    
    	// the result of this:
    	switch (TyQueThdBean21.getRefResult()) {
                  
        case 0: Msg.setText(tyQueThdBundle.getString("case_0__Msg_text"));
                  break;                    
        
        case 1: Msg.setText(tyQueThdBundle.getString("case_1__Msg_text"));
                  break;                    
        
        case 2: Msg.setText(tyQueThdBundle.getString("case_2__Msg_text"));
                  break;                    
        
        case 3: Msg.setText(tyQueThdBundle.getString("case_3__Msg_text")); 

								// enable the enable button
								EnableButton.setEnabled(true);

								// done
                break;
                  
    	} // end-switch     


		} catch (java.lang.Exception e) {
		}
	}
	void TheList_valueChanged(javax.swing.event.ListSelectionEvent event)
	{
		// to do: code goes here.
			 
		TheList_valueChanged_Interaction1(event);
	}
	void TheList_valueChanged_Interaction1(javax.swing.event.ListSelectionEvent event)
	{
		try {
				// When something selected
				if  (TheList.getSelectedIndex() >= 0) {
						
						// enable for disable function
						DisableButton.setEnabled(true);
						EnableSpecificButton.setEnabled(true);
				}
				else {
							// disable for disable function
							DisableButton.setEnabled(false);
							EnableSpecificButton.setEnabled(false);

				} // endif			

		} catch (java.lang.Exception e) {
		}
	}
  void TyQueThd_windowClosing(java.awt.event.WindowEvent event)
  {
    // to do: code goes here.
       
    TyQueThd_windowClosing_Interaction1(event);
  }
  void TyQueThd_windowClosing_Interaction1(java.awt.event.WindowEvent event) {
    try {
      this.exitApplication();
    } catch (Exception e) {
    }
  }
}
