package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyQueMaintBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyQueMaint_title", "Tymeac Queue Maintenance"},
		{"OpenCfgFile_title", "Open Tymeac Configuration File"},
		{"OpenCfgFile_directory", ""},
		{"OpenCfgFile_file", "tymeac.xml"},
		{"PACNameLabel_text", "Class Name"},
		{"PACNameLabel_toolTipText", ""},
		{"ThreadLabel_text", "<--- THREADS --->"},
		{"ThreadLabel_toolTipText", ""},
		{"WaitListsLabel_text", "<--- WAIT  LISTS --->"},
		{"WaitListsLabel_toolTipText", ""},
		{"Msg_text", " Enter a Queue Name"},
		{"Msg_toolTipText", ""},
		{"QueText_text", ""},
		{"QueText_toolTipText", "Enter a Queue Name"},
		{"ImportButton_text", "Import"},
		{"ImportButton_actionCommand", "Import"},
		{"ImportButton_toolTipText", "Import an existing Queue"},
		{"DeleteButton_text", "Delete"},
		{"DeleteButton_actionCommand", "Delete"},
		{"DeleteButton_toolTipText", "Delete this Queue"},
		{"FinishButton_text", "Finish"},
		{"FinishButton_actionCommand", "Finish"},
		{"FinishButton_toolTipText", "Add/Update Queue"},
		{"QueLabel_text", "Queue Name"},
		{"QueLabel_toolTipText", ""},
		{"ApplText_text", ""},
		{"ApplText_toolTipText", "Processing Application Class"},
		{"ApplLabel_text", "<-------------------------------------- Processing Application Class ----------------------------------------------->"},
		{"ApplLabel_toolTipText", ""},
		{"AgentBox_text", "   Output Agent ?"},
		{"AgentBox_actionCommand", "   Output Agent"},
		{"AgentBox_toolTipText", "Is this an Output Agent Queue?"},
		{"ThreadsText_text", ""},
		{"ThreadsText_toolTipText", "Total number of threads for this Queue"},
		{"ThreadsLabel_text", "# of Threads"},
		{"ThreadsLabel_toolTipText", ""},
		{"StartBox_text", "   Initially start all threads?"},
		{"StartBox_actionCommand", "   Initially start all threads?"},
		{"StartBox_toolTipText", "Start all the Queue\'s threads at Tymeac Start Up"},
		{"IdleText_text", ""},
		{"IdleText_toolTipText", "Seconds to wait before inactivating "},
		{"IdleLabel_text", "Idle Wait Time"},
		{"IdleLabel_toolTipText", ""},
		{"KillText_text", ""},
		{"KillText_toolTipText", "Idle seconds before thread destroy"},
		{"KillLabel_text", "Idle Thread Life"},
		{"KillLabel_toolTipText", ""},
    
		{"NbrWLText_text", ""},
		{"NbrWLText_toolTipText", "Total number of Wait Lists"},
		{"NbrWlLabel_text", "# of Wait Lists"},
		{"NbrWlLabel_toolTipText", ""},
    
		{"NbrInText_text", ""},
		{"NbrInText_toolTipText", "Nbr physical entries in each Wait List"},
		{"NbrInLabel_text", "# physical"},
		{"NbrInLabel_toolTipText", ""},
    
    {"TNbrInText_text", ""},
    {"TNbrInText_toolTipText", "Nbr logical entries in each Wait List"},
    {"TNbrInLabel_text", "# logical"},
    {"TNbrInLabel_toolTipText", ""},
    
		{"OverallText_text", "00"},
		{"OverallText_toolTipText", "00 - 99"},
		{"IndividualText_text", "00"},
		{"IndividualText_toolTipText", "00 - 99"},
		{"FactorText_text", "00"},
		{"FactorText_toolTipText", "00 - 99"},
		{"AverageText_text", "00"},
		{"AverageText_toolTipText", "00 - 99"},
		{"OverallLabel_text", "Overall %"},
		{"OverallLabel_toolTipText", ""},
		{"IndividualLabel_text", "Individual %"},
		{"IndividualLabel_toolTipText", ""},
		{"ThreshLabel_text", "<-------------------- T H R E S H O L D S  ------------------->"},
		{"ThreshLabel_toolTipText", ""},
		{"FactorLabel_text", "Weighted Factor"},
		{"FactorLabel_toolTipText", ""},
		{"AverageLabel_text", "Weighted Average"},
		{"AverageLabel_toolTipText", ""},
		{"TimeoutText_text", ""},
		{"TimeoutText_toolTipText", ""},
		{"TimeoutLabel_text", "Timeout Value"},
		{"TimeoutLabel_toolTipText", ""},
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"Msg_text_1", " Configuration file error"},
		{"Msg_text_2", " Error fetching dir and filename"},
		{"Msg_text_3", "Error reading Cfg File"},
		{"th_putOut", "TyQueMaint.html"},
		{"Msg_text_4", " Enter a Queue to import"},
		{"case_0__Msg_text", " Make Changes"},
		{"case_1__Msg_text", " Configuration File not found"},
		{"case_2__Msg_text", " Invalid Queue for Import"},
		{"case_3__Msg_text", " Queue DataBase error"},
		{"Msg_text_5", " Enter a Queue to delete"},
		{"case_0__Msg_text_1", " Queue \'"},
		{"deleted", "\' deleted"},
		{"QueText_text_1", ""},
		{"ApplText_text_1", ""},
		{"TimeoutText_text_1", ""},
		{"ThreadsText_text_1", ""},
		{"IdleText_text_1", ""},
		{"KillText_text_1", ""},
		{"NbrWLText_text_1", ""},
		{"NbrInText_text_1", ""},
		{"OverallText_text_1", "0.00"},
		{"IndividualText_text_1", "0.00"},
		{"FactorText_text_1", "0.00"},
		{"AverageText_text_1", "0.00"},
		{"case_1__Msg_text_1", " Configuration File not found"},
		{"case_2__Msg_text_1", " Invalid Queue Name"},
		{"case_3__Msg_text_1", " Queue DataBase error"},
		{"case_4__Msg_text", " Import Queue first"},
		{"Msg_text_6", " Enter a Queue Name to add"},
		{"case_0__Msg_text_2", " Successful"},
		{"case_1__Msg_text_2", " Configuration File not found"},
		{"case_2__Msg_text_2", " Queue Name Invalid"},
		{"case_3__Msg_text_2", " Database Error"},
		{"case_4__Msg_text_1", " Invalid number of Wait Lists"},
		{"case_5__Msg_text", " Invalid number of WL entries"},
		{"case_6__Msg_text", " Invalid number of Threads"},
		{"case_7__Msg_text", " Queue Name cannot be changed"},
		{"case_8__Msg_text", " Invalid Overall %"},
		{"case_9__Msg_text", " Invalid Individual %"},
		{"case_10___Msg_text", " Invalid Weighted Factor"},
		{"case_11___Msg_text", " Invalid Weighted Average"},
		{"case_12___Msg_text", " Enter a Processing Application Class"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
