package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

import java.awt.*;
import javax.swing.*;
import com.tymeac.base.*;
/**
 * The Queue Maintenance display frame.
 */
public class TyQueMaint extends javax.swing.JFrame
{
  private static final long serialVersionUID = 1L;

  // Used by addNotify
  boolean frameSizeAdjusted = false;

  //{{DECLARE_CONTROLS
	java.awt.FileDialog OpenCfgFile = new java.awt.FileDialog(this);
	javax.swing.JLabel PACNameLabel = new javax.swing.JLabel();
	javax.swing.JLabel ThreadLabel = new javax.swing.JLabel();
	javax.swing.JLabel WaitListsLabel = new javax.swing.JLabel();
	javax.swing.JLabel Msg = new javax.swing.JLabel();
	javax.swing.JTextField QueText = new javax.swing.JTextField();
	javax.swing.JButton ImportButton = new javax.swing.JButton();
	javax.swing.JButton DeleteButton = new javax.swing.JButton();
	javax.swing.JButton FinishButton = new javax.swing.JButton();
	javax.swing.JLabel QueLabel = new javax.swing.JLabel();
	javax.swing.JTextField ApplText = new javax.swing.JTextField();
	javax.swing.JLabel ApplLabel = new javax.swing.JLabel();
	javax.swing.JCheckBox AgentBox = new javax.swing.JCheckBox();
	javax.swing.JTextField ThreadsText = new javax.swing.JTextField();
	javax.swing.JLabel ThreadsLabel = new javax.swing.JLabel();
	javax.swing.JCheckBox StartBox = new javax.swing.JCheckBox();
	javax.swing.JTextField IdleText = new javax.swing.JTextField();
	javax.swing.JLabel IdleLabel = new javax.swing.JLabel();
	javax.swing.JTextField KillText = new javax.swing.JTextField();
	javax.swing.JLabel KillLabel = new javax.swing.JLabel();
	javax.swing.JTextField NbrWLText = new javax.swing.JTextField();
	javax.swing.JLabel NbrWlLabel = new javax.swing.JLabel();
  
	javax.swing.JTextField NbrInText = new javax.swing.JTextField();
	javax.swing.JLabel NbrInLabel = new javax.swing.JLabel();
  
  javax.swing.JTextField TNbrInText = new javax.swing.JTextField();
  javax.swing.JLabel TNbrInLabel = new javax.swing.JLabel();
  
	javax.swing.JTextField OverallText = new javax.swing.JTextField();
	javax.swing.JTextField IndividualText = new javax.swing.JTextField();
	javax.swing.JTextField FactorText = new javax.swing.JTextField();
	javax.swing.JTextField AverageText = new javax.swing.JTextField();
	javax.swing.JLabel OverallLabel = new javax.swing.JLabel();
	javax.swing.JLabel IndividualLabel = new javax.swing.JLabel();
	javax.swing.JLabel ThreshLabel = new javax.swing.JLabel();
	javax.swing.JLabel FactorLabel = new javax.swing.JLabel();
	javax.swing.JLabel AverageLabel = new javax.swing.JLabel();
	javax.swing.JTextField TimeoutText = new javax.swing.JTextField();
	javax.swing.JLabel TimeoutLabel = new javax.swing.JLabel();
	javax.swing.JMenuBar JMenuBar1 = new javax.swing.JMenuBar();
	javax.swing.JMenu fileMenu = new javax.swing.JMenu();
	javax.swing.JMenuItem exitItem = new javax.swing.JMenuItem();
	javax.swing.JSeparator JSeparator1 = new javax.swing.JSeparator();
	javax.swing.JMenu helpMenu = new javax.swing.JMenu();
	javax.swing.JMenuItem Help = new javax.swing.JMenuItem();
	javax.swing.JMenuItem about = new javax.swing.JMenuItem();
	//}}

	TyQueMaintBean2 TyQueMaintBean21 = null;
  TyCfgFields base = null;
  String ty_dir = null;
  String ty_file = null; 

  class SymWindow extends java.awt.event.WindowAdapter
  {
    public void windowClosing(java.awt.event.WindowEvent event)
    {
      Object object = event.getSource();
      if (object == TyQueMaint.this)
        TyQueMaint_windowClosing(event);
    }
  }

  class SymAction implements java.awt.event.ActionListener
  {
    public void actionPerformed(java.awt.event.ActionEvent event)
    { 
      Object object = event.getSource();
      if (object == exitItem)
        exitItem_actionPerformed(event);
      else if (object == Help)
        Help_actionPerformed(event);
      else  if (object == about)
        about_actionPerformed(event);
			else if (object == ImportButton)
				ImportButton_actionPerformed(event);
			else if (object == DeleteButton)
				DeleteButton_actionPerformed(event);
			else if (object == FinishButton)
				FinishButton_actionPerformed(event);      
      
    }
  }

	static java.util.ResourceBundle tyQueMaintBundle = java.util.ResourceBundle.getBundle("com.tymeac.client.jframe.TyQueMaintBundle");
  public TyQueMaint()
  {
    // This code is automatically generated by Visual Cafe when you add
    // components to the visual environment. It instantiates and initializes
    // the components. To modify the code, only use code syntax that matches
    // what Visual Cafe can generate, or Visual Cafe may be unable to back
    // parse your Java file into its visual environment.
    //{{INIT_CONTROLS
    setJMenuBar(JMenuBar1);
    setTitle(tyQueMaintBundle.getString("TyQueMaint_title"));
    setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    getContentPane().setLayout(null);
    setSize(760,444);
		setVisible(false);
    //$$ JMenuBar1.move(120,540);
    fileMenu.setText(tyQueMaintBundle.getString("fileMenu_text"));
    fileMenu.setActionCommand(tyQueMaintBundle.getString("fileMenu_actionCommand"));
		fileMenu.setToolTipText(tyQueMaintBundle.getString("fileMenu_toolTipText").length() != 0 ? tyQueMaintBundle.getString("fileMenu_toolTipText") : null);
    fileMenu.setMnemonic((int)'F');
    JMenuBar1.add(fileMenu);
    
    fileMenu.add(JSeparator1);
    
    exitItem.setText(tyQueMaintBundle.getString("exitItem_text"));
    exitItem.setActionCommand(tyQueMaintBundle.getString("exitItem_actionCommand"));
		exitItem.setToolTipText(tyQueMaintBundle.getString("exitItem_toolTipText").length() != 0 ? tyQueMaintBundle.getString("exitItem_toolTipText") : null);
    exitItem.setMnemonic((int)'X');
    fileMenu.add(exitItem);
		JSeparator1.setToolTipText(tyQueMaintBundle.getString("JSeparator1_toolTipText").length() != 0 ? tyQueMaintBundle.getString("JSeparator1_toolTipText") : null);
    
    helpMenu.setText(tyQueMaintBundle.getString("helpMenu_text"));
    helpMenu.setActionCommand(tyQueMaintBundle.getString("helpMenu_actionCommand"));
		helpMenu.setToolTipText(tyQueMaintBundle.getString("helpMenu_toolTipText").length() != 0 ? tyQueMaintBundle.getString("helpMenu_toolTipText") : null);
    helpMenu.setMnemonic((int)'H');
    JMenuBar1.add(helpMenu);
    
    fileMenu.add(JSeparator1);
       
    Help.setText(tyQueMaintBundle.getString("Help_text"));
    Help.setActionCommand(tyQueMaintBundle.getString("Help_actionCommand"));
		Help.setToolTipText(tyQueMaintBundle.getString("Help_toolTipText").length() != 0 ? tyQueMaintBundle.getString("Help_toolTipText") : null);
    Help.setMnemonic((int)'D');
    helpMenu.add(Help);
    
    fileMenu.add(JSeparator1);
    
    about.setText(tyQueMaintBundle.getString("about_text"));
    about.setActionCommand(tyQueMaintBundle.getString("about_actionCommand"));
		about.setToolTipText(tyQueMaintBundle.getString("about_toolTipText").length() != 0 ? tyQueMaintBundle.getString("about_toolTipText") : null);
    about.setMnemonic((int)'A');
    helpMenu.add(about); 
		PACNameLabel.setText(tyQueMaintBundle.getString("PACNameLabel_text"));
		PACNameLabel.setToolTipText(tyQueMaintBundle.getString("PACNameLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("PACNameLabel_toolTipText") : null);
		getContentPane().add(PACNameLabel);
		PACNameLabel.setBounds(24,125,80,15);
		ThreadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		ThreadLabel.setText(tyQueMaintBundle.getString("ThreadLabel_text"));
		ThreadLabel.setToolTipText(tyQueMaintBundle.getString("ThreadLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("ThreadLabel_toolTipText") : null);
		getContentPane().add(ThreadLabel);
		ThreadLabel.setFont(new Font("Dialog", Font.BOLD, 14));
		ThreadLabel.setBounds(96,156,120,24);
    
		WaitListsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		WaitListsLabel.setText(tyQueMaintBundle.getString("WaitListsLabel_text"));
		WaitListsLabel.setToolTipText(tyQueMaintBundle.getString("WaitListsLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("WaitListsLabel_toolTipText") : null);
		getContentPane().add(WaitListsLabel);
		WaitListsLabel.setFont(new Font("Dialog", Font.BOLD, 14));
		WaitListsLabel.setBounds(485,156,180,24); // 432
    
		Msg.setText(tyQueMaintBundle.getString("Msg_text"));
		Msg.setToolTipText(tyQueMaintBundle.getString("Msg_toolTipText").length() != 0 ? tyQueMaintBundle.getString("Msg_toolTipText") : null);
		getContentPane().add(Msg);
		Msg.setForeground(new java.awt.Color(128,0,0));
		Msg.setBounds(12,384,612,36);
		QueText.setText(tyQueMaintBundle.getString("QueText_text"));
		QueText.setToolTipText(tyQueMaintBundle.getString("QueText_toolTipText").length() != 0 ? tyQueMaintBundle.getString("QueText_toolTipText") : null);
		getContentPane().add(QueText);
		QueText.setBounds(30,20,438,28);
		ImportButton.setText(tyQueMaintBundle.getString("ImportButton_text"));
		ImportButton.setActionCommand(tyQueMaintBundle.getString("ImportButton_actionCommand"));
		ImportButton.setToolTipText(tyQueMaintBundle.getString("ImportButton_toolTipText").length() != 0 ? tyQueMaintBundle.getString("ImportButton_toolTipText") : null);
		getContentPane().add(ImportButton);
		ImportButton.setBounds(552,20,80,30);
		DeleteButton.setText(tyQueMaintBundle.getString("DeleteButton_text"));
		DeleteButton.setActionCommand(tyQueMaintBundle.getString("DeleteButton_actionCommand"));
		DeleteButton.setToolTipText(tyQueMaintBundle.getString("DeleteButton_toolTipText").length() != 0 ? tyQueMaintBundle.getString("DeleteButton_toolTipText") : null);
		getContentPane().add(DeleteButton);
		DeleteButton.setBounds(660,20,80,30);
		FinishButton.setText(tyQueMaintBundle.getString("FinishButton_text"));
		FinishButton.setActionCommand(tyQueMaintBundle.getString("FinishButton_actionCommand"));
		FinishButton.setToolTipText(tyQueMaintBundle.getString("FinishButton_toolTipText").length() != 0 ? tyQueMaintBundle.getString("FinishButton_toolTipText") : null);
		getContentPane().add(FinishButton);
		FinishButton.setBounds(660,384,80,30);
		QueLabel.setText(tyQueMaintBundle.getString("QueLabel_text"));
		QueLabel.setToolTipText(tyQueMaintBundle.getString("QueLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("QueLabel_toolTipText") : null);
		getContentPane().add(QueLabel);
		QueLabel.setBounds(30,50,200,20);
		ApplText.setText(tyQueMaintBundle.getString("ApplText_text"));
		ApplText.setToolTipText(tyQueMaintBundle.getString("ApplText_toolTipText").length() != 0 ? tyQueMaintBundle.getString("ApplText_toolTipText") : null);
		getContentPane().add(ApplText);
		ApplText.setBounds(24,96,438,28);
		ApplLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		ApplLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		ApplLabel.setText(tyQueMaintBundle.getString("ApplLabel_text"));
		ApplLabel.setToolTipText(tyQueMaintBundle.getString("ApplLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("ApplLabel_toolTipText") : null);
		getContentPane().add(ApplLabel);
		ApplLabel.setFont(new Font("Dialog", Font.BOLD, 14));
		ApplLabel.setBounds(24,72,660,24);
		AgentBox.setText(tyQueMaintBundle.getString("AgentBox_text"));
		AgentBox.setActionCommand(tyQueMaintBundle.getString("AgentBox_actionCommand"));
		AgentBox.setToolTipText(tyQueMaintBundle.getString("AgentBox_toolTipText").length() != 0 ? tyQueMaintBundle.getString("AgentBox_toolTipText") : null);
		getContentPane().add(AgentBox);
		AgentBox.setFont(new Font("Dialog", Font.PLAIN, 12));
		AgentBox.setBounds(588,108,120,16);
		ThreadsText.setText(tyQueMaintBundle.getString("ThreadsText_text"));
		ThreadsText.setToolTipText(tyQueMaintBundle.getString("ThreadsText_toolTipText").length() != 0 ? tyQueMaintBundle.getString("ThreadsText_toolTipText") : null);
		getContentPane().add(ThreadsText);
		ThreadsText.setBounds(24,180,40,30);
		ThreadsLabel.setText(tyQueMaintBundle.getString("ThreadsLabel_text"));
		ThreadsLabel.setToolTipText(tyQueMaintBundle.getString("ThreadsLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("ThreadsLabel_toolTipText") : null);
		getContentPane().add(ThreadsLabel);
		ThreadsLabel.setBounds(24,210,84,24);
		StartBox.setText(tyQueMaintBundle.getString("StartBox_text"));
		StartBox.setActionCommand(tyQueMaintBundle.getString("StartBox_actionCommand"));
		StartBox.setToolTipText(tyQueMaintBundle.getString("StartBox_toolTipText").length() != 0 ? tyQueMaintBundle.getString("StartBox_toolTipText") : null);
		getContentPane().add(StartBox);
		StartBox.setFont(new Font("Dialog", Font.PLAIN, 12));
		StartBox.setBounds(96,240,168,24);
		IdleText.setText(tyQueMaintBundle.getString("IdleText_text"));
		IdleText.setToolTipText(tyQueMaintBundle.getString("IdleText_toolTipText").length() != 0 ? tyQueMaintBundle.getString("IdleText_toolTipText") : null);
		getContentPane().add(IdleText);
		IdleText.setBounds(120,180,40,30);
		IdleLabel.setText(tyQueMaintBundle.getString("IdleLabel_text"));
		IdleLabel.setToolTipText(tyQueMaintBundle.getString("IdleLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("IdleLabel_toolTipText") : null);
		getContentPane().add(IdleLabel);
		IdleLabel.setBounds(120,210,80,20);
		KillText.setText(tyQueMaintBundle.getString("KillText_text"));
		KillText.setToolTipText(tyQueMaintBundle.getString("KillText_toolTipText").length() != 0 ? tyQueMaintBundle.getString("KillText_toolTipText") : null);
		getContentPane().add(KillText);
		KillText.setBounds(228,180,40,30);
		KillLabel.setText(tyQueMaintBundle.getString("KillLabel_text"));
		KillLabel.setToolTipText(tyQueMaintBundle.getString("KillLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("KillLabel_toolTipText") : null);
		getContentPane().add(KillLabel);
		KillLabel.setBounds(228,210,100,20);
		NbrWLText.setText(tyQueMaintBundle.getString("NbrWLText_text"));
		NbrWLText.setToolTipText(tyQueMaintBundle.getString("NbrWLText_toolTipText").length() != 0 ? tyQueMaintBundle.getString("NbrWLText_toolTipText") : null);
		getContentPane().add(NbrWLText);
		NbrWLText.setBounds(456,180,40,30);
		NbrWlLabel.setText(tyQueMaintBundle.getString("NbrWlLabel_text"));
		NbrWlLabel.setToolTipText(tyQueMaintBundle.getString("NbrWlLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("NbrWlLabel_toolTipText") : null);
		getContentPane().add(NbrWlLabel);
		NbrWlLabel.setBounds(456,210,96,24);
    
    // physical
		NbrInText.setText(tyQueMaintBundle.getString("NbrInText_text"));
		NbrInText.setToolTipText(tyQueMaintBundle.getString("NbrInText_toolTipText").length() != 0 ? tyQueMaintBundle.getString("NbrInText_toolTipText") : null);
		getContentPane().add(NbrInText);
		NbrInText.setBounds(552,180,40,30);
    
		NbrInLabel.setText(tyQueMaintBundle.getString("NbrInLabel_text"));
		NbrInLabel.setToolTipText(tyQueMaintBundle.getString("NbrInLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("NbrInLabel_toolTipText") : null);
		getContentPane().add(NbrInLabel);
		NbrInLabel.setBounds(552,210,130,20);
    
    // logical
    TNbrInText.setText(tyQueMaintBundle.getString("TNbrInText_text"));
    TNbrInText.setToolTipText(tyQueMaintBundle.getString("TNbrInText_toolTipText").length() != 0 ? tyQueMaintBundle.getString("TNbrInText_toolTipText") : null);
    getContentPane().add(TNbrInText);
    TNbrInText.setBounds(645,180,40,30); // 552
    
    TNbrInLabel.setText(tyQueMaintBundle.getString("TNbrInLabel_text"));
    TNbrInLabel.setToolTipText(tyQueMaintBundle.getString("TNbrInLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("TNbrInLabel_toolTipText") : null);
    getContentPane().add(TNbrInLabel);
    TNbrInLabel.setBounds(645,210,130,20); // 552
        
		OverallText.setText(tyQueMaintBundle.getString("OverallText_text"));
		OverallText.setToolTipText(tyQueMaintBundle.getString("OverallText_toolTipText").length() != 0 ? tyQueMaintBundle.getString("OverallText_toolTipText") : null);
		getContentPane().add(OverallText);
		OverallText.setBounds(192,300,40,30);
		IndividualText.setText(tyQueMaintBundle.getString("IndividualText_text"));
		IndividualText.setToolTipText(tyQueMaintBundle.getString("IndividualText_toolTipText").length() != 0 ? tyQueMaintBundle.getString("IndividualText_toolTipText") : null);
		getContentPane().add(IndividualText);
		IndividualText.setBounds(300,300,40,30);
		FactorText.setText(tyQueMaintBundle.getString("FactorText_text"));
		FactorText.setToolTipText(tyQueMaintBundle.getString("FactorText_toolTipText").length() != 0 ? tyQueMaintBundle.getString("FactorText_toolTipText") : null);
		getContentPane().add(FactorText);
		FactorText.setBounds(408,300,40,30);
		AverageText.setText(tyQueMaintBundle.getString("AverageText_text"));
		AverageText.setToolTipText(tyQueMaintBundle.getString("AverageText_toolTipText").length() != 0 ? tyQueMaintBundle.getString("AverageText_toolTipText") : null);
		getContentPane().add(AverageText);
		AverageText.setBounds(516,300,40,30);
		OverallLabel.setText(tyQueMaintBundle.getString("OverallLabel_text"));
		OverallLabel.setToolTipText(tyQueMaintBundle.getString("OverallLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("OverallLabel_toolTipText") : null);
		getContentPane().add(OverallLabel);
		OverallLabel.setBounds(192,330,60,24);
		IndividualLabel.setText(tyQueMaintBundle.getString("IndividualLabel_text"));
		IndividualLabel.setToolTipText(tyQueMaintBundle.getString("IndividualLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("IndividualLabel_toolTipText") : null);
		getContentPane().add(IndividualLabel);
		IndividualLabel.setBounds(300,330,84,24);
		ThreshLabel.setText(tyQueMaintBundle.getString("ThreshLabel_text"));
		ThreshLabel.setToolTipText(tyQueMaintBundle.getString("ThreshLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("ThreshLabel_toolTipText") : null);
		getContentPane().add(ThreshLabel);
		ThreshLabel.setFont(new Font("Dialog", Font.BOLD, 14));
		ThreshLabel.setBounds(192,276,360,24);
		FactorLabel.setText(tyQueMaintBundle.getString("FactorLabel_text"));
		FactorLabel.setToolTipText(tyQueMaintBundle.getString("FactorLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("FactorLabel_toolTipText") : null);
		getContentPane().add(FactorLabel);
		FactorLabel.setBounds(408,330,110,20);
		AverageLabel.setText(tyQueMaintBundle.getString("AverageLabel_text"));
		AverageLabel.setToolTipText(tyQueMaintBundle.getString("AverageLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("AverageLabel_toolTipText") : null);
		getContentPane().add(AverageLabel);
		AverageLabel.setBounds(516,330,110,20);
		TimeoutText.setText(tyQueMaintBundle.getString("TimeoutText_text"));
		TimeoutText.setToolTipText(tyQueMaintBundle.getString("TimeoutText_toolTipText").length() != 0 ? tyQueMaintBundle.getString("TimeoutText_toolTipText") : null);
		OpenCfgFile.setMode(FileDialog.LOAD);
		OpenCfgFile.setTitle(tyQueMaintBundle.getString("OpenCfgFile_title"));
		OpenCfgFile.setDirectory(tyQueMaintBundle.getString("OpenCfgFile_directory"));
		OpenCfgFile.setFile(tyQueMaintBundle.getString("OpenCfgFile_file"));
		//$$ OpenCfgFile.move(12,540);
		getContentPane().add(TimeoutText);
		TimeoutText.setBounds(492,96,84,30);
		TimeoutLabel.setText(tyQueMaintBundle.getString("TimeoutLabel_text"));
		TimeoutLabel.setToolTipText(tyQueMaintBundle.getString("TimeoutLabel_toolTipText").length() != 0 ? tyQueMaintBundle.getString("TimeoutLabel_toolTipText") : null);
		getContentPane().add(TimeoutLabel);
		TimeoutLabel.setBounds(492,125,96,12);
		JMenuBar1.setToolTipText(tyQueMaintBundle.getString("JMenuBar1_toolTipText").length() != 0 ? tyQueMaintBundle.getString("JMenuBar1_toolTipText") : null);
		//$$ OpenFileDialog.move(0,481);

    //}}

		Msg.setBorder(new javax.swing.border.EtchedBorder());

    //{{INIT_MENUS
    //}}

    //{{REGISTER_LISTENERS
    SymWindow aSymWindow = new SymWindow();
    this.addWindowListener(aSymWindow);
    
    SymAction lSymAction = new SymAction();
    exitItem.addActionListener(lSymAction);
    Help.addActionListener(lSymAction);
    about.addActionListener(lSymAction);
		ImportButton.addActionListener(lSymAction);
		DeleteButton.addActionListener(lSymAction);
		FinishButton.addActionListener(lSymAction);
		//}}
  }
    /**
     * Creates a new instance of JFrame1 with the given title.
     * @param sTitle the title for the new frame.
     */
  public TyQueMaint(String sTitle)
  {
    this();
    setTitle(sTitle);
  }
   void about_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    about_actionPerformed_Interaction1(event);
  }
  void about_actionPerformed_Interaction1(java.awt.event.ActionEvent event) { 
  
    try {
      // TymeacAbout Create with owner and show as modal
      {
        TyAbout TyAbout1 = new TyAbout(this);
        TyAbout1.setModal(true);
        TyAbout1.setVisible(true);
      }
    } catch (Exception e) {
    }
  }
    /**
     * Notifies this component that it has been added to a container
     * This method should be called by <code>Container.add</code>, and 
     * not by user code directly.
     * Overridden here to adjust the size of the frame if needed.
     * @see java.awt.Container#removeNotify
     */
  public void addNotify()
  {
    // Record the size of the window prior to calling parents addNotify.
    Dimension size = getSize();
    
    super.addNotify();
    
    if (frameSizeAdjusted)
      return;
    frameSizeAdjusted = true;
    
    // Adjust size of frame according to the insets and menu bar
    javax.swing.JMenuBar menuBar = getRootPane().getJMenuBar();
    int menuBarHeight = 0;
    if (menuBar != null)
        menuBarHeight = menuBar.getPreferredSize().height;
    Insets insets = getInsets();
    setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height + menuBarHeight);
  }
	// basic stuff for me
  int basicFile() {
      
  		try {
          // Show the FileDialog
          OpenCfgFile.setVisible(true);

		  } // end-try

	    catch (java.lang.Exception e) {

	    		// say error
          Msg.setText(tyQueMaintBundle.getString("Msg_text_1"));

	        // done 
          return 1;

      } // end-catch

      try {
         // get the dir and file name
         ty_dir = OpenCfgFile.getDirectory();

         ty_file = OpenCfgFile.getFile();

      } // end-try

      catch (java.lang.Exception e) {

      		// say so
          Msg.setText(tyQueMaintBundle.getString("Msg_text_2"));

          // done
          return 1;

	    } // end-catch

      // new base of the cfg fields
      TyCfgFields xbase = new TyCfgFields();

			// do the file read and load
	    int reason = TyCfgFileIO.getFile(ty_dir, ty_file, xbase);

     // when no good
     if  (reason > 0) {

         // put the message
         TyCfgFileIO.putMsg(reason, ty_dir, ty_file);

          // say so
          Msg.setText(tyQueMaintBundle.getString("Msg_text_3"));

          // done
          return 1;

      } // endif 

      // when first
      if  (TyQueMaintBean21 == null) {

          // get a new obj
          TyQueMaintBean21 = new TyQueMaintBean2(xbase);

      } // endif

      // save the cfg fields
      base = xbase;

      // good
      return 0;

	} // end-method
	void DeleteButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		DeleteButton_actionPerformed_Interaction1(event);
	}
	void DeleteButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
			// text field to string
        String queData = QueText.getText();

        // When no data
	      if  ((queData == null) ||
             (queData.length() < 1)) {

             // say so
	           Msg.setText(tyQueMaintBundle.getString("Msg_text_5"));

	          // done
	          return;
	      
				} // endif

	      // When need cfg file
	      if  (base == null) {

	          // When basic stuff failed
	          if  (basicFile() != 0) {

	              // get out
		            return;

	          } // endif
	      } // endif

	      TyQueMaintBean21.deleteButton(QueText);

        // what came back
	      switch (TyQueMaintBean21.getDelResult()) {

	          case 0: Msg.setText(tyQueMaintBundle.getString("case_0__Msg_text_1") + queData + tyQueMaintBundle.getString("deleted"));      
									
										// null fields
										QueText.setText(tyQueMaintBundle.getString("QueText_text_1"));
										ApplText.setText(tyQueMaintBundle.getString("ApplText_text_1"));
										TimeoutText.setText(tyQueMaintBundle.getString("TimeoutText_text_1"));										
										AgentBox.setSelected(false);
										StartBox.setSelected(false);
										ThreadsText.setText(tyQueMaintBundle.getString("ThreadsText_text_1"));
										IdleText.setText(tyQueMaintBundle.getString("IdleText_text_1"));
										KillText.setText(tyQueMaintBundle.getString("KillText_text_1"));
										NbrWLText.setText(tyQueMaintBundle.getString("NbrWLText_text_1"));
										NbrInText.setText(tyQueMaintBundle.getString("NbrInText_text_1"));
                    TNbrInText.setText(tyQueMaintBundle.getString("TNbrInText_text_1"));
										OverallText.setText(tyQueMaintBundle.getString("OverallText_text_1"));
										IndividualText.setText(tyQueMaintBundle.getString("IndividualText_text_1"));
										FactorText.setText(tyQueMaintBundle.getString("FactorText_text_1"));
										AverageText.setText(tyQueMaintBundle.getString("AverageText_text_1"));
							
										// done 
						      	return;
                  
        		case 1: Msg.setText(tyQueMaintBundle.getString("case_1__Msg_text_1"));  
                  return;           
    
        		case 2: Msg.setText(tyQueMaintBundle.getString("case_2__Msg_text_1"));
                  return;
        
        		case 3: Msg.setText(tyQueMaintBundle.getString("case_3__Msg_text_1"));
                  return;

						case 4: Msg.setText(tyQueMaintBundle.getString("case_4__Msg_text"));
                  return;

				} // end-switch

		} catch (java.lang.Exception e) {
		}
	}
  //{{DECLARE_MENUS
	//}}

  void exitApplication()
  {    
    this.setVisible(false);    // hide the Frame
    this.dispose();            // free the system resources
    System.exit(0);            // close the application 
    
  }
  void exitItem_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    exitItem_actionPerformed_Interaction1(event);
  }
  void exitItem_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
    try {
      this.exitApplication();
    } catch (Exception e) {
    }
  }
	void FinishButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		FinishButton_actionPerformed_Interaction1(event);
	}
	void FinishButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
			// text field to string
        String queData = QueText.getText();

        // When no data
	      if  ((queData == null) ||
             (queData.length() < 1)) {

             // say so
	           Msg.setText(tyQueMaintBundle.getString("Msg_text_6"));

	          // done
	          return;
	      
				} // endif

	      // When need cfg file
	      if  (base == null) {

	          // When basic stuff failed
	          if  (basicFile() != 0) {

	              // get out
		            return;

	          } // endif
	      } // endif

	      TyQueMaintBean21.finishButton(QueText,
																			ApplText,
																			TimeoutText,
																			AgentBox,
																			StartBox,
																			ThreadsText,
																			IdleText,
																			KillText,
																			NbrWLText,
																			NbrInText,
                                      TNbrInText,
																			OverallText,
																			IndividualText,
																			FactorText,
																			AverageText);

        // what came back
	      switch (TyQueMaintBean21.getUpdResult()) {

	          case 0: Msg.setText(
                  queData
                  + " "
                  + tyQueMaintBundle.getString("case_0__Msg_text_2"));
                  break;                    
            
        		case 1: Msg.setText(tyQueMaintBundle.getString("case_1__Msg_text_2")); 
                    break;
        
        		case 2: Msg.setText(tyQueMaintBundle.getString("case_2__Msg_text_2")); 
                  break;          
                  
        		case 3: Msg.setText(tyQueMaintBundle.getString("case_3__Msg_text_2")); 
            	      break;  
        
        		case 4: Msg.setText(tyQueMaintBundle.getString("case_4__Msg_text_1")); 
            	      break;
                
        		case 5: Msg.setText(tyQueMaintBundle.getString("case_5__Msg_text")); 
            	      break;
                  
        		case 6: Msg.setText(tyQueMaintBundle.getString("case_6__Msg_text")); 
            	      break;
        
        		case 7: Msg.setText(tyQueMaintBundle.getString("case_7__Msg_text")); 
            	      break;

        		case 8: Msg.setText(tyQueMaintBundle.getString("case_8__Msg_text")); 
            	      break;

        		case 9: Msg.setText(tyQueMaintBundle.getString("case_9__Msg_text")); 
            	      break;

        		case 10:  Msg.setText(tyQueMaintBundle.getString("case_10___Msg_text")); 
            	      break;

        		case 11:  Msg.setText(tyQueMaintBundle.getString("case_11___Msg_text")); 
            	      break;

						case 12:  Msg.setText(tyQueMaintBundle.getString("case_12___Msg_text")); 
            	      break;
              
				} // end-switch
                 
		} catch (java.lang.Exception e) {
		}
	}
  void Help_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    Help_actionPerformed_Interaction1(event);
  }
  void Help_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
    
    TyHelp th = new TyHelp();

    th.putOut(tyQueMaintBundle.getString("th_putOut"));
    
  }
	void ImportButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		ImportButton_actionPerformed_Interaction1(event);
	}
	void ImportButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
				// text field to string
        String queData = QueText.getText();


        // When no data
	      if  ((queData == null) ||
             (queData.length() < 1)) {

             // say so
	           Msg.setText(tyQueMaintBundle.getString("Msg_text_4"));

	          // done
	          return;
	      
				} // endif

	      // When need cfg file
	      if  (base == null) {

	          // When basic stuff failed
	          if  (basicFile() != 0) {

	              // get out
		            return;

	          } // endif
	      } // endif

	      TyQueMaintBean21.importButton(QueText,
																			ApplText,
																			TimeoutText,
																			AgentBox,
																			StartBox,
																			ThreadsText,
																			IdleText,
																			KillText,
																			NbrWLText,
																			NbrInText,
                                      TNbrInText,
																			OverallText,
																			IndividualText,
																			FactorText,
																			AverageText);

        // what came back
	      switch (TyQueMaintBean21.getImpResult()) {

	          case 0: Msg.setText(tyQueMaintBundle.getString("case_0__Msg_text"));      
                  return;
                  
        		case 1: Msg.setText(tyQueMaintBundle.getString("case_1__Msg_text"));  
                  return;           
    
        		case 2: Msg.setText(tyQueMaintBundle.getString("case_2__Msg_text"));
                  return;
        
        		case 3: Msg.setText(tyQueMaintBundle.getString("case_3__Msg_text"));
                  return;

				} // end-switch
                 

		} catch (java.lang.Exception e) {
		}
	}
  /**
   * The entry point for this application.
   * Sets the Look and Feel to the System Look and Feel.
   * Creates a new JFrame1 and makes it visible.
   */
  static public void main(String args[])
  {
    try {
        // Add the following code if you want the Look and Feel
        // to be set to the Look and Feel of the native system.
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (Exception e) { 
        }
        

      //Create a new instance of our application's frame, and make it visible.
      (new TyQueMaint()).setVisible(true);
    } 
    catch (Throwable t) {
      t.printStackTrace();
      //Ensure the application exits with an error condition.
      System.exit(1);
    }
  }
  void TyQueMaint_windowClosing(java.awt.event.WindowEvent event)
  {
    // to do: code goes here.
       
    TyQueMaint_windowClosing_Interaction1(event);
  }
  void TyQueMaint_windowClosing_Interaction1(java.awt.event.WindowEvent event) {
    try {
      this.exitApplication();
    } catch (Exception e) {
    }
  }
}
