package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2008 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

import java.awt.*;
import javax.swing.*;
import com.tymeac.base.*;

/**
 * The Alter Queue Data display frame.
 */
public class TyQueData extends javax.swing.JFrame
{
  private static final long serialVersionUID = 1L;

  // Used by addNotify
  boolean frameSizeAdjusted = false;

  //{{DECLARE_CONTROLS
	javax.swing.JTextField QueText = new javax.swing.JTextField();
	javax.swing.JButton ImportButton = new javax.swing.JButton();
	javax.swing.JButton UpdateButton = new javax.swing.JButton();
	javax.swing.JLabel ThresholdLabel = new javax.swing.JLabel();
	javax.swing.JLabel ThreadsLabel = new javax.swing.JLabel();
	javax.swing.JLabel WaitlistsLabel = new javax.swing.JLabel();
	javax.swing.JTextField OverallText = new javax.swing.JTextField();
	javax.swing.JTextField FactorText = new javax.swing.JTextField();
	javax.swing.JTextField WaitText = new javax.swing.JTextField();
	javax.swing.JTextField NbrText = new javax.swing.JTextField();
	javax.swing.JTextField IndividualText = new javax.swing.JTextField();
	javax.swing.JTextField AverageText = new javax.swing.JTextField();
	javax.swing.JTextField IdleText = new javax.swing.JTextField();
	javax.swing.JLabel QueLabel = new javax.swing.JLabel();
	javax.swing.JLabel OverallLabel = new javax.swing.JLabel();
	javax.swing.JLabel JLabel1 = new javax.swing.JLabel();
	javax.swing.JLabel FactorLabel = new javax.swing.JLabel();
	javax.swing.JLabel AverageLabel = new javax.swing.JLabel();
	javax.swing.JLabel WaitLabel = new javax.swing.JLabel();
	javax.swing.JLabel IdleLabel = new javax.swing.JLabel();
	javax.swing.JLabel NbrLabel = new javax.swing.JLabel();
  
  // new threshold wait list fields
  javax.swing.JLabel TNbrLabel = new javax.swing.JLabel();
  javax.swing.JTextField TNbrText = new javax.swing.JTextField();
  
  // new timeout fields
  javax.swing.JLabel PACLabel = new javax.swing.JLabel();
  javax.swing.JTextField TimeoutText = new javax.swing.JTextField();
  javax.swing.JLabel TimeoutLabel = new javax.swing.JLabel();
    
	javax.swing.JLabel Msg = new javax.swing.JLabel();
	javax.swing.JMenuBar JMenuBar1 = new javax.swing.JMenuBar();
	javax.swing.JMenu fileMenu = new javax.swing.JMenu();
	javax.swing.JMenuItem exitItem = new javax.swing.JMenuItem();
	javax.swing.JSeparator JSeparator1 = new javax.swing.JSeparator();
	javax.swing.JMenu helpMenu = new javax.swing.JMenu();
	javax.swing.JMenuItem Help = new javax.swing.JMenuItem();
	javax.swing.JMenuItem about = new javax.swing.JMenuItem();
	//}}

  TyQueDataBean2 TyQueDataBean21 = null;
	TymeacInterface Ti = null;

  class SymWindow extends java.awt.event.WindowAdapter
  {
    public void windowClosing(java.awt.event.WindowEvent event)
    {
      Object object = event.getSource();
      if (object == TyQueData.this)
        TyQueData_windowClosing(event);
    }
  }

  class SymAction implements java.awt.event.ActionListener
  {
    public void actionPerformed(java.awt.event.ActionEvent event)
    { 
      Object object = event.getSource();
      if (object == exitItem)
        exitItem_actionPerformed(event);
      else if (object == Help)
        Help_actionPerformed(event);
      else  if (object == about)
        about_actionPerformed(event);
      else if (object == ImportButton)
        ImportButton_actionPerformed(event);
      else if (object == UpdateButton)
        UpdateButton_actionPerformed(event);
      
    }
  }

	static java.util.ResourceBundle tyQueDataBundle = java.util.ResourceBundle.getBundle("com.tymeac.client.jframe.TyQueDataBundle");
  public TyQueData()
  {
    // This code is automatically generated by Visual Cafe when you add
    // components to the visual environment. It instantiates and initializes
    // the components. To modify the code, only use code syntax that matches
    // what Visual Cafe can generate, or Visual Cafe may be unable to back
    // parse your Java file into its visual environment.
    //{{INIT_CONTROLS
    setJMenuBar(JMenuBar1);
    setTitle(tyQueDataBundle.getString("TyQueData_title"));
    setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    getContentPane().setLayout(null);
    setSize(600,370);
    setVisible(false);
    
		QueText.setText(tyQueDataBundle.getString("QueText_text"));
		QueText.setToolTipText(tyQueDataBundle.getString("QueText_toolTipText").length() != 0 ? tyQueDataBundle.getString("QueText_toolTipText") : null);
		getContentPane().add(QueText);
		QueText.setBounds(24,24,348,30);
    
    ImportButton.setText(tyQueDataBundle.getString("ImportButton_text"));
    getContentPane().add(ImportButton);
    ImportButton.setBounds(396,24,80,30);
    UpdateButton.setText(tyQueDataBundle.getString("UpdateButton_text"));
    
    getContentPane().add(UpdateButton);
    UpdateButton.setBounds(504,24,80,30);
    
    //$$ JMenuBar1.move(144,468);
    fileMenu.setText(tyQueDataBundle.getString("fileMenu_text"));
    fileMenu.setActionCommand(tyQueDataBundle.getString("fileMenu_actionCommand"));
		fileMenu.setToolTipText(tyQueDataBundle.getString("fileMenu_toolTipText").length() != 0 ? tyQueDataBundle.getString("fileMenu_toolTipText") : null);
    fileMenu.setMnemonic((int)'F');
    JMenuBar1.add(fileMenu);
    
    fileMenu.add(JSeparator1);
    
    exitItem.setText(tyQueDataBundle.getString("exitItem_text"));
    exitItem.setActionCommand(tyQueDataBundle.getString("exitItem_actionCommand"));
		exitItem.setToolTipText(tyQueDataBundle.getString("exitItem_toolTipText").length() != 0 ? tyQueDataBundle.getString("exitItem_toolTipText") : null);
    exitItem.setMnemonic((int)'X');
    fileMenu.add(exitItem);
		JSeparator1.setToolTipText(tyQueDataBundle.getString("JSeparator1_toolTipText").length() != 0 ? tyQueDataBundle.getString("JSeparator1_toolTipText") : null);
    
    helpMenu.setText(tyQueDataBundle.getString("helpMenu_text"));
    helpMenu.setActionCommand(tyQueDataBundle.getString("helpMenu_actionCommand"));
		helpMenu.setToolTipText(tyQueDataBundle.getString("helpMenu_toolTipText").length() != 0 ? tyQueDataBundle.getString("helpMenu_toolTipText") : null);
    helpMenu.setMnemonic((int)'H');
    JMenuBar1.add(helpMenu);
    
    fileMenu.add(JSeparator1);
       
    Help.setText(tyQueDataBundle.getString("Help_text"));
    Help.setActionCommand(tyQueDataBundle.getString("Help_actionCommand"));
		Help.setToolTipText(tyQueDataBundle.getString("Help_toolTipText").length() != 0 ? tyQueDataBundle.getString("Help_toolTipText") : null);
    Help.setMnemonic((int)'D');
    helpMenu.add(Help);
    
    fileMenu.add(JSeparator1);
    
    about.setText(tyQueDataBundle.getString("about_text"));
    about.setActionCommand(tyQueDataBundle.getString("about_actionCommand"));
		about.setToolTipText(tyQueDataBundle.getString("about_toolTipText").length() != 0 ? tyQueDataBundle.getString("about_toolTipText") : null);
    about.setMnemonic((int)'A');
    helpMenu.add(about);
    
		ThresholdLabel.setText(tyQueDataBundle.getString("ThresholdLabel_text"));
		ThresholdLabel.setToolTipText(tyQueDataBundle.getString("ThresholdLabel_toolTipText").length() != 0 ? tyQueDataBundle.getString("ThresholdLabel_toolTipText") : null);
		getContentPane().add(ThresholdLabel);
		ThresholdLabel.setFont(new Font("Dialog", Font.BOLD, 14));
		ThresholdLabel.setBounds(216,84,156,24);
    
		ThreadsLabel.setText(tyQueDataBundle.getString("ThreadsLabel_text"));
		ThreadsLabel.setToolTipText(tyQueDataBundle.getString("ThreadsLabel_toolTipText").length() != 0 ? tyQueDataBundle.getString("ThreadsLabel_toolTipText") : null);
		getContentPane().add(ThreadsLabel);
		ThreadsLabel.setFont(new Font("Dialog", Font.BOLD, 14));
		ThreadsLabel.setBounds(35,204,120,24); //24
    
		WaitlistsLabel.setText(tyQueDataBundle.getString("WaitlistsLabel_text"));
		WaitlistsLabel.setToolTipText(tyQueDataBundle.getString("WaitlistsLabel_toolTipText").length() != 0 ? tyQueDataBundle.getString("WaitlistsLabel_toolTipText") : null);
		getContentPane().add(WaitlistsLabel);
		WaitlistsLabel.setFont(new Font("Dialog", Font.BOLD, 14));
		WaitlistsLabel.setBounds(235,204,154,24); //372
    
    // timeout label
    PACLabel.setText(tyQueDataBundle.getString("PACLabel_text"));
    PACLabel.setToolTipText(tyQueDataBundle.getString("PACLabel_toolTipText").length() != 0 ? tyQueDataBundle.getString("ThreadsLabel_toolTipText") : null);
    getContentPane().add(PACLabel);
    PACLabel.setFont(new Font("Dialog", Font.BOLD, 14));
    PACLabel.setBounds(460,204,120,24); 
    
    // timeout fields
    TimeoutLabel.setText(tyQueDataBundle.getString("TimeoutLabel_text"));
    TimeoutLabel.setToolTipText(tyQueDataBundle.getString("TimeoutLabel_toolTipText").length() != 0 ? tyQueDataBundle.getString("TimeoutLabel_toolTipText") : null);
    getContentPane().add(TimeoutLabel);
    TimeoutLabel.setBounds(470,270,100,20); 
    
    TimeoutText.setText(tyQueDataBundle.getString("TimeoutText_text"));
    TimeoutText.setToolTipText(tyQueDataBundle.getString("TimeoutText_toolTipText").length() != 0 ? tyQueDataBundle.getString("TimeoutText_toolTipText") : null);
    getContentPane().add(TimeoutText);
    TimeoutText.setBounds(470,240,60,30); //72    
    
    ImportButton.setActionCommand(tyQueDataBundle.getString("ImportButton_actionCommand"));
    ImportButton.setToolTipText(tyQueDataBundle.getString("ImportButton_toolTipText").length() != 0 ? tyQueDataBundle.getString("ImportButton_toolTipText") : null);
    
    UpdateButton.setActionCommand(tyQueDataBundle.getString("UpdateButton_actionCommand"));
    UpdateButton.setToolTipText(tyQueDataBundle.getString("UpdateButton_toolTipText").length() != 0 ? tyQueDataBundle.getString("UpdateButton_toolTipText") : null);
    
    OverallText.setText(tyQueDataBundle.getString("OverallText_text"));
    OverallText.setToolTipText(tyQueDataBundle.getString("OverallText_toolTipText").length() != 0 ? tyQueDataBundle.getString("OverallText_toolTipText") : null);
    getContentPane().add(OverallText);
    OverallText.setBounds(96,120,40,30);
    
		FactorText.setText(tyQueDataBundle.getString("FactorText_text"));
    FactorText.setToolTipText(tyQueDataBundle.getString("FactorText_toolTipText").length() != 0 ? tyQueDataBundle.getString("FactorText_toolTipText") : null);
    getContentPane().add(FactorText);
    FactorText.setBounds(312,120,40,30);
    
		WaitText.setText(tyQueDataBundle.getString("WaitText_text"));
    WaitText.setToolTipText(tyQueDataBundle.getString("WaitText_toolTipText").length() != 0 ? tyQueDataBundle.getString("WaitText_toolTipText") : null);
    getContentPane().add(WaitText);
    WaitText.setBounds(24,240,40,30); //72
    
		NbrText.setText(tyQueDataBundle.getString("NbrText_text"));
    NbrText.setToolTipText(tyQueDataBundle.getString("NbrText_toolTipText").length() != 0 ? tyQueDataBundle.getString("NbrText_toolTipText") : null);
    getContentPane().add(NbrText);
    NbrText.setBounds(250,240,40,30); //286
    
    // threshold wl lable
    TNbrLabel.setText(tyQueDataBundle.getString("TNbrLabel_text"));
    TNbrLabel.setToolTipText(tyQueDataBundle.getString("TNbrLabel_toolTipText").length() != 0 ? tyQueDataBundle.getString("NbrLabel_toolTipText") : null);
    getContentPane().add(TNbrLabel);
    TNbrLabel.setBounds(330,270,100,20); //286 
    
    // threshold wl text
    TNbrText.setText(tyQueDataBundle.getString("TNbrText_text"));
    TNbrText.setToolTipText(tyQueDataBundle.getString("TNbrText_toolTipText").length() != 0 ? tyQueDataBundle.getString("TNbrText_toolTipText") : null);
    getContentPane().add(TNbrText);
    TNbrText.setBounds(330,240,40,30); //286
        
		IndividualText.setText(tyQueDataBundle.getString("IndividualText_text"));
    IndividualText.setToolTipText(tyQueDataBundle.getString("IndividualText_toolTipText").length() != 0 ? tyQueDataBundle.getString("IndividualText_toolTipText") : null);
    getContentPane().add(IndividualText);
    IndividualText.setBounds(204,120,40,30);
    
		AverageText.setText(tyQueDataBundle.getString("AverageText_text"));
    AverageText.setToolTipText(tyQueDataBundle.getString("AverageText_toolTipText").length() != 0 ? tyQueDataBundle.getString("AverageText_toolTipText") : null);
    getContentPane().add(AverageText);
    AverageText.setBounds(420,120,40,30);
    
		IdleText.setText(tyQueDataBundle.getString("IdleText_text"));
    IdleText.setToolTipText(tyQueDataBundle.getString("IdleText_toolTipText").length() != 0 ? tyQueDataBundle.getString("IdleText_toolTipText") : null);
    getContentPane().add(IdleText);
    IdleText.setBounds(120,240,40,30); //168
    
    QueLabel.setText(tyQueDataBundle.getString("QueLabel_text"));
		QueLabel.setToolTipText(tyQueDataBundle.getString("QueLabel_toolTipText").length() != 0 ? tyQueDataBundle.getString("QueLabel_toolTipText") : null);
    getContentPane().add(QueLabel);
    QueLabel.setBounds(24,55,100,20);
    
    OverallLabel.setText(tyQueDataBundle.getString("OverallLabel_text"));
		OverallLabel.setToolTipText(tyQueDataBundle.getString("OverallLabel_toolTipText").length() != 0 ? tyQueDataBundle.getString("OverallLabel_toolTipText") : null);
    getContentPane().add(OverallLabel);
    OverallLabel.setBounds(96,150,60,20);
    
    JLabel1.setText(tyQueDataBundle.getString("JLabel1_text"));
		JLabel1.setToolTipText(tyQueDataBundle.getString("JLabel1_toolTipText").length() != 0 ? tyQueDataBundle.getString("JLabel1_toolTipText") : null);
    getContentPane().add(JLabel1);
    JLabel1.setBounds(204,150,72,20);
    
    FactorLabel.setText(tyQueDataBundle.getString("FactorLabel_text"));
		FactorLabel.setToolTipText(tyQueDataBundle.getString("FactorLabel_toolTipText").length() != 0 ? tyQueDataBundle.getString("FactorLabel_toolTipText") : null);
    getContentPane().add(FactorLabel);
    FactorLabel.setBounds(312,150,100,20);
    
    AverageLabel.setText(tyQueDataBundle.getString("AverageLabel_text"));
		AverageLabel.setToolTipText(tyQueDataBundle.getString("AverageLabel_toolTipText").length() != 0 ? tyQueDataBundle.getString("AverageLabel_toolTipText") : null);
    getContentPane().add(AverageLabel);
    AverageLabel.setBounds(420,150,110,20);
    
    WaitLabel.setText(tyQueDataBundle.getString("WaitLabel_text"));
		WaitLabel.setToolTipText(tyQueDataBundle.getString("WaitLabel_toolTipText").length() != 0 ? tyQueDataBundle.getString("WaitLabel_toolTipText") : null);
    getContentPane().add(WaitLabel);
    WaitLabel.setBounds(24,270,100,20); //72
    
    IdleLabel.setText(tyQueDataBundle.getString("IdleLabel_text"));
		IdleLabel.setToolTipText(tyQueDataBundle.getString("IdleLabel_toolTipText").length() != 0 ? tyQueDataBundle.getString("IdleLabel_toolTipText") : null);
    getContentPane().add(IdleLabel);
    IdleLabel.setBounds(120,270,100,20); //168
    
    NbrLabel.setText(tyQueDataBundle.getString("NbrLabel_text"));
		NbrLabel.setToolTipText(tyQueDataBundle.getString("NbrLabel_toolTipText").length() != 0 ? tyQueDataBundle.getString("NbrLabel_toolTipText") : null);
    getContentPane().add(NbrLabel);
    NbrLabel.setBounds(250,270,100,20); //286    
    
    
    Msg.setText(tyQueDataBundle.getString("Msg_text"));
		Msg.setToolTipText(tyQueDataBundle.getString("Msg_toolTipText").length() != 0 ? tyQueDataBundle.getString("Msg_toolTipText") : null);
    getContentPane().add(Msg);
    Msg.setForeground(new java.awt.Color(128,0,0));
    Msg.setBounds(12,324,380,30);
    
		JMenuBar1.setToolTipText(tyQueDataBundle.getString("JMenuBar1_toolTipText").length() != 0 ? tyQueDataBundle.getString("JMenuBar1_toolTipText") : null);

    //}}

		Msg.setBorder(new javax.swing.border.EtchedBorder());		

    //{{INIT_MENUS
    //}}

    //{{REGISTER_LISTENERS
    SymWindow aSymWindow = new SymWindow();
    this.addWindowListener(aSymWindow);
    
    SymAction lSymAction = new SymAction();
    exitItem.addActionListener(lSymAction);
    Help.addActionListener(lSymAction);
    about.addActionListener(lSymAction);
    ImportButton.addActionListener(lSymAction);
    UpdateButton.addActionListener(lSymAction);
    //}}
  }
    public TyQueData(TymeacInterface TyI)
    {
				this();
    		Ti = TyI;

    		try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (Exception e) { 
        }
    }
    /**
     * Creates a new instance of JFrame1 with the given title.
     * @param sTitle the title for the new frame.
     */
  public TyQueData(String sTitle)
  {
    this();
    setTitle(sTitle);
  }
   void about_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    about_actionPerformed_Interaction1(event);
  }
  void about_actionPerformed_Interaction1(java.awt.event.ActionEvent event) { 
  
    try {
      // TymeacAbout Create with owner and show as modal
      {
        TyAbout TyAbout1 = new TyAbout(this);
        TyAbout1.setModal(true);
        TyAbout1.setVisible(true);
      }
    } catch (Exception e) {
    }
  }
    /**
     * Notifies this component that it has been added to a container
     * This method should be called by <code>Container.add</code>, and 
     * not by user code directly.
     * Overridden here to adjust the size of the frame if needed.
     * @see java.awt.Container#removeNotify
     */
  public void addNotify()
  {
    // Record the size of the window prior to calling parents addNotify.
    Dimension size = getSize();
    
    super.addNotify();
    
    if (frameSizeAdjusted)
      return;
    frameSizeAdjusted = true;
    
    // Adjust size of frame according to the insets and menu bar
    javax.swing.JMenuBar menuBar = getRootPane().getJMenuBar();
    int menuBarHeight = 0;
    if (menuBar != null)
        menuBarHeight = menuBar.getPreferredSize().height;
    Insets insets = getInsets();
    setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height + menuBarHeight);
  }
  //{{DECLARE_MENUS
	//}}

  void exitApplication()
  {    
    this.setVisible(false);    // hide the Frame
    this.dispose();            // free the system resources
		if  (Ti == null) {
    		System.exit(0);   // close the application 
		} // endif    
  }
  void exitItem_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    exitItem_actionPerformed_Interaction1(event);
  }
  void exitItem_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
    try {
      this.exitApplication();
    } catch (Exception e) {
    }
  }
  void Help_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    Help_actionPerformed_Interaction1(event);
  }
  void Help_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
    
    TyHelp th = new TyHelp();

    th.putOut(tyQueDataBundle.getString("th_putOut"));
    
  }
  void ImportButton_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    ImportButton_actionPerformed_Interaction1(event);
  }
  void ImportButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
  {
    try {
        // first
        if  (TyQueDataBean21 == null) {
			
						// When internal
          	if  (Ti != null) {

              // get the obj
              TyQueDataBean21 = new TyQueDataBean2(Ti);
          	}
          	else {
          		 // get the obj
            	 TyQueDataBean21 = new TyQueDataBean2();

            } // endif
        } // endif 

        // must have the queue name
        String qName = QueText.getText();

        if  (qName.length() < 1) {

            Msg.setText(tyQueDataBundle.getString("Msg_text_1"));

            // done
            return;

        } // endif
        
    // do the function
    TyQueDataBean21.importButton( QueText,
                                  WaitText,
                                  IdleText,
                                  OverallText,
                                  IndividualText,
                                  FactorText,
                                  AverageText,
                                  NbrText,
                                  TNbrText,
                                  TimeoutText);
    
    // the result of this:
    switch (TyQueDataBean21.getImpResult()) {
                  
        case 0: Msg.setText(tyQueDataBundle.getString("case_0__Msg_text"));
                  break;                    
        
        case 1: Msg.setText(tyQueDataBundle.getString("case_1__Msg_text"));
                  break;                    
              
        case 2: Msg.setText(tyQueDataBundle.getString("case_2__Msg_text")); 
                  break;
        
        case 3: Msg.setText(tyQueDataBundle.getString("case_3__Msg_text")); 
                  break;          
      
    } // end-switch 


    } catch (java.lang.Exception e) {
    }
  }
  /**
   * The entry point for this application.
   * Sets the Look and Feel to the System Look and Feel.
   * Creates a new JFrame1 and makes it visible.
   */
  static public void main(String args[])
  {
    try {
        // Add the following code if you want the Look and Feel
        // to be set to the Look and Feel of the native system.
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (Exception e) { 
        }
        

      //Create a new instance of our application's frame, and make it visible.
      (new TyQueData()).setVisible(true);
    } 
    catch (Throwable t) {
      t.printStackTrace();
      //Ensure the application exits with an error condition.
      System.exit(1);
    }
  }
  void TyQueData_windowClosing(java.awt.event.WindowEvent event)
  {
    // to do: code goes here.
       
    TyQueData_windowClosing_Interaction1(event);
  }
  void TyQueData_windowClosing_Interaction1(java.awt.event.WindowEvent event) {
    try {
      this.exitApplication();
    } catch (Exception e) {
    }
  }
  void UpdateButton_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    UpdateButton_actionPerformed_Interaction1(event);
  }
  void UpdateButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
  {
    try {
      // first
        if  (TyQueDataBean21 == null) {

            Msg.setText(tyQueDataBundle.getString("Msg_text_2"));

            // done
            return;

        } // endif 

        // must have the queue name
        String qName = QueText.getText();

        if  (qName.length() < 1) {

            Msg.setText(tyQueDataBundle.getString("Msg_text_3"));

            // done
            return;

        } // endif
        
      // do the function
      TyQueDataBean21.updateButton( QueText,
                                  WaitText,
                                  IdleText,
                                  OverallText,
                                  IndividualText,
                                  FactorText,
                                  AverageText,
                                  NbrText,
                                  TNbrText,
                                  TimeoutText);
    
      // the result of this:
      switch (TyQueDataBean21.getUpdResult()) {
                  
        case 0: Msg.setText(tyQueDataBundle.getString("case_0__Msg_text_1"));
                  break;                    
        
        case 1: Msg.setText(tyQueDataBundle.getString("case_1__Msg_text_1"));
                  break;                    
              
        case 2: Msg.setText(tyQueDataBundle.getString("case_2__Msg_text_1")); 
                  break;
        
        case 3: Msg.setText(tyQueDataBundle.getString("case_3__Msg_text_1")); 
                  break;          
      
        case 4: Msg.setText(tyQueDataBundle.getString("case_4__Msg_text")); 
                  break;

        case 5: Msg.setText(tyQueDataBundle.getString("case_5__Msg_text")); 
                  break;

        case 6: Msg.setText(tyQueDataBundle.getString("case_6__Msg_text")); 
                  break;  

        case 7: Msg.setText(tyQueDataBundle.getString("case_7__Msg_text")); 
                  break;  

        case 8: Msg.setText(tyQueDataBundle.getString("case_8__Msg_text")); 
                  break;  

        case 9: Msg.setText(tyQueDataBundle.getString("case_9__Msg_text")); 
                  break;  

        case 10: Msg.setText(tyQueDataBundle.getString("case_10__Msg_text")); 
                  break;  
                  
        case 11: Msg.setText(tyQueDataBundle.getString("case_11__Msg_text")); 
                  break;  
                  
        case 12: Msg.setText(tyQueDataBundle.getString("case_12__Msg_text")); 
                  break;           
      
    } // end-switch 

    } catch (java.lang.Exception e) {
    }
  }
}
