package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2008 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyQueDataBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyQueData_title", "Tymeac Queue Elements Update"},
		{"QueText_text", ""},
		{"QueText_toolTipText", "Enter a Queue Name"},
		{"ImportButton_text", "Import"},
		{"ImportButton_actionCommand", "Import"},
		{"ImportButton_toolTipText", "Import an existing Queue"},
		{"UpdateButton_text", "Update"},
		{"UpdateButton_actionCommand", "Update"},
		{"UpdateButton_toolTipText", "Update the fields"},
		{"ThresholdLabel_text", "<--- Thresholds --->"},
		{"ThresholdLabel_toolTipText", ""},
		{"ThreadsLabel_text", "<--- Threads --->"},
		{"ThreadsLabel_toolTipText", ""},
		{"WaitlistsLabel_text", "<--- Wait Lists Size --->"},
    
    {"PACLabel_text", "<--- Appl. --->"},
    {"PACLabel_toolTipText", ""},
    {"TimeoutLabel_text", "Appl Timeout"},
    {"TimeoutLabel_toolTipText", ""},
    {"TimeoutText_text", ""},
    {"TimeoutText_toolTipText", "time in seconds"},
    
		{"WaitlistsLabel_toolTipText", ""},
		{"OverallText_text", ""},
		{"OverallText_toolTipText", "0 - 99"},
		{"FactorText_text", ""},
		{"FactorText_toolTipText", "00 - 99"},
		{"WaitText_text", ""},
		{"WaitText_toolTipText", "time in seconds"},
    
		{"NbrText_text", ""},
		{"NbrText_toolTipText", "1 - ~"},
    
    {"TNbrText_text", ""},
    {"TNbrText_toolTipText", "1 - physical"},
    
		{"IndividualText_text", ""},
		{"IndividualText_toolTipText", "0 - 99"},
		{"AverageText_text", ""},
		{"AverageText_toolTipText", "00 - 99"},
		{"IdleText_text", ""},
		{"IdleText_toolTipText", "time in seconds"},
		{"QueLabel_text", "Queue Name"},
		{"QueLabel_toolTipText", ""},
		{"OverallLabel_text", "Overall %"},
		{"OverallLabel_toolTipText", ""},
		{"JLabel1_text", "Individual %"},
		{"JLabel1_toolTipText", ""},
		{"FactorLabel_text", "Weighted Factor"},
		{"FactorLabel_toolTipText", ""},
		{"AverageLabel_text", "Weighted Average"},
		{"AverageLabel_toolTipText", ""},
		{"WaitLabel_text", "Idle Wait Time"},
		{"WaitLabel_toolTipText", ""},
		{"IdleLabel_text", "Idle Thread Life"},
		{"IdleLabel_toolTipText", ""},
		{"NbrLabel_text", "Physical"},
		{"NbrLabel_toolTipText", ""},
    
    {"TNbrLabel_text", "Logical"},
    {"TNbrLabel_toolTipText", ""},
    
		{"Msg_text", " Enter a Queue Name"},
		{"Msg_toolTipText", ""},
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"th_putOut", "TyQueData.html"},
		{"Msg_text_1", " Queue Name must be entered"},
		{"case_0__Msg_text", " Connection failure"},
		{"case_1__Msg_text", " Tymeac shutting down"},
		{"case_2__Msg_text", " Invalid Queue Name"},
		{"case_3__Msg_text", " Make changes"},
		{"Msg_text_2", " Must Import a Queue first"},
		{"Msg_text_3", " Queue Name must be entered"},
		{"case_0__Msg_text_1", " Connection failure"},
		{"case_1__Msg_text_1", " Tymeac shutting down"},
		{"case_2__Msg_text_1", " Invalid Queue Name"},
		{"case_3__Msg_text_1", " Invalid Queue for update"},
		{"case_4__Msg_text", " Successful"},
		{"case_5__Msg_text", " Invalid Number of WL entries"},
		{"case_6__Msg_text", " Cannot alter WL entries at this time"},
		{"case_7__Msg_text", " Invalid Overall %"},
		{"case_8__Msg_text", " Invalid Individual %"},
		{"case_9__Msg_text", " Invalid Weighted Factor"},
		{"case_10__Msg_text", " Invalid Weighted Average"},
    {"case_11__Msg_text", " Invalid Appl timeout value"},
    {"case_12__Msg_text", " Invalid Nmb WL entries for thresholds"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
