package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyQueThdBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyQueThd_title", "Tymeac Queue Threads Data"},
		{"QueText_text", ""},
		{"QueText_toolTipText", "Enter a Queue Name"},
		{"QueLabel_text", "Queue Name"},
		{"QueLabel_toolTipText", ""},
		{"RefreshButton_text", "Refresh"},
		{"RefreshButton_actionCommand", "Refresh"},
		{"RefreshButton_toolTipText", "Refresh the list"},
		{"DisableButton_text", "Disable Selected"},
		{"DisableButton_actionCommand", "Disable Selected"},
		{"DisableButton_toolTipText", "Disable the selected Queue Thread"},
		
		{"EnableButton_text", "Enable All"},
		{"EnableButton_actionCommand", "Enable All"},
		{"EnableButton_toolTipText", "Enable all disabled Queue Threads"},
		
		{"EnableSpecificButton_text", "Enable Selected"},
    {"EnableSpecificButton_actionCommand", "Enable Selected"},
    {"EnableSpecificButton_toolTipText", "Enable selected Queue Thread"},
		
		{"Msg_text", " Enter a Queue name"},
		{"Msg_toolTipText", ""},
		{"JScrollPane1_toolTipText", ""},
		{"TheList_toolTipText", ""},
		{"ListLabel_text", "Id, (#_Proc\'d) - Status"},
		{"ListLabel_toolTipText", ""},
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"th_putOut", "TyQueThd.html"},
		{"Msg_text_1", " Enter a Queue Name first"},
		{"case_0__Msg_text", " Connection failure"},
		{"case_1__Msg_text", " Tymeac shutting down"},
		{"case_2__Msg_text", " Invalid Queue Name"},
		{"case_3__Msg_text", " Select Thread"},
		{"case_0__Msg_text_1", " Invalid Queue Name"},
		{"case_1__Msg_text_1", " Selected Thread invalid"},
		{"case_2__Msg_text_1", " Use Refresh first"},
		{"case_3__Msg_text_1", " Connection failure"},
		{"case_4__Msg_text", " Select a thread"},
		{"case_5__Msg_text", " Tymeac shutting down"},
		{"case_0__Msg_text_2", " OK"},
		{"case_1__Msg_text_2", " Connection failure"},
		{"case_2__Msg_text_2", " Tymeac shutting down"},
		{"case_3__Msg_text_2", " Queue Name invalid"},
		{"case_4__Msg_text_1", " Use Refresh first"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
