package com.tymeac.client.jframe;

import java.awt.*;
import javax.swing.*;
import com.tymeac.base.*;

/**
 * 
 */
public class TyShutdown extends javax.swing.JFrame
{
  private static final long serialVersionUID = 1L;

    public TyShutdown(TymeacInterface TyI)
    {
				this();
    	Ti = TyI;

    	try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (Exception e) { 
        }
    }

  public TyShutdown()
  {
    // This code is automatically generated by Visual Cafe when you add
    // components to the visual environment. It instantiates and initializes
    // the components. To modify the code, only use code syntax that matches
    // what Visual Cafe can generate, or Visual Cafe may be unable to back
    // parse your Java file into its visual environment.
    //{{INIT_CONTROLS
    setJMenuBar(JMenuBar1);
    setTitle(tyShutdownBundle.getString("TyShutdown_title"));
    setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    getContentPane().setLayout(null);
    setSize(440,190);
		setVisible(false);
		ShutButton.setText(tyShutdownBundle.getString("ShutButton_text"));
		ShutButton.setToolTipText(tyShutdownBundle.getString("ShutButton_toolTipText").length() != 0 ? tyShutdownBundle.getString("ShutButton_toolTipText") : null);
		getContentPane().add(ShutButton);
		ShutButton.setBounds(36,48,125,40);
		Msg.setText(tyShutdownBundle.getString("Msg_text"));
		Msg.setToolTipText(tyShutdownBundle.getString("Msg_toolTipText").length() != 0 ? tyShutdownBundle.getString("Msg_toolTipText") : null);
		getContentPane().add(Msg);
		Msg.setForeground(new java.awt.Color(128,0,0));
		Msg.setBounds(20,144,400,30);
		JMenuBar1.setToolTipText(tyShutdownBundle.getString("JMenuBar1_toolTipText").length() != 0 ? tyShutdownBundle.getString("JMenuBar1_toolTipText") : null);
    //$$ JMenuBar1.move(168,312);
    fileMenu.setText(tyShutdownBundle.getString("fileMenu_text"));
    fileMenu.setActionCommand(tyShutdownBundle.getString("fileMenu_actionCommand"));
		fileMenu.setToolTipText(tyShutdownBundle.getString("fileMenu_toolTipText").length() != 0 ? tyShutdownBundle.getString("fileMenu_toolTipText") : null);
    fileMenu.setMnemonic((int)'F');
    JMenuBar1.add(fileMenu);
    
    fileMenu.add(JSeparator1);
    
    exitItem.setText(tyShutdownBundle.getString("exitItem_text"));
    exitItem.setActionCommand(tyShutdownBundle.getString("exitItem_actionCommand"));
		exitItem.setToolTipText(tyShutdownBundle.getString("exitItem_toolTipText").length() != 0 ? tyShutdownBundle.getString("exitItem_toolTipText") : null);
    exitItem.setMnemonic((int)'X');
    fileMenu.add(exitItem);
		JSeparator1.setToolTipText(tyShutdownBundle.getString("JSeparator1_toolTipText").length() != 0 ? tyShutdownBundle.getString("JSeparator1_toolTipText") : null);
    
    helpMenu.setText(tyShutdownBundle.getString("helpMenu_text"));
    helpMenu.setActionCommand(tyShutdownBundle.getString("helpMenu_actionCommand"));
		helpMenu.setToolTipText(tyShutdownBundle.getString("helpMenu_toolTipText").length() != 0 ? tyShutdownBundle.getString("helpMenu_toolTipText") : null);
    helpMenu.setMnemonic((int)'H');
    JMenuBar1.add(helpMenu);
    
    fileMenu.add(JSeparator1);
       
    Help.setText(tyShutdownBundle.getString("Help_text"));
    Help.setActionCommand(tyShutdownBundle.getString("Help_actionCommand"));
		Help.setToolTipText(tyShutdownBundle.getString("Help_toolTipText").length() != 0 ? tyShutdownBundle.getString("Help_toolTipText") : null);
    Help.setMnemonic((int)'D');
    helpMenu.add(Help);
    
    fileMenu.add(JSeparator1);
    
    about.setText(tyShutdownBundle.getString("about_text"));
    about.setActionCommand(tyShutdownBundle.getString("about_actionCommand"));
		about.setToolTipText(tyShutdownBundle.getString("about_toolTipText").length() != 0 ? tyShutdownBundle.getString("about_toolTipText") : null);
    about.setMnemonic((int)'A');
    helpMenu.add(about); 
		KillButton.setText(tyShutdownBundle.getString("KillButton_text"));
		KillButton.setActionCommand(tyShutdownBundle.getString("KillButton_actionCommand"));
		KillButton.setToolTipText(tyShutdownBundle.getString("KillButton_toolTipText").length() != 0 ? tyShutdownBundle.getString("KillButton_toolTipText") : null);
		getContentPane().add(KillButton);
		KillButton.setBounds(288,48,125,40);
		ShutButton.setActionCommand(tyShutdownBundle.getString("ShutButton_actionCommand"));

    //}}

		Msg.setBorder(new javax.swing.border.EtchedBorder());

    //{{INIT_MENUS
    //}}

    //{{REGISTER_LISTENERS
    SymWindow aSymWindow = new SymWindow();
    this.addWindowListener(aSymWindow);
    
    SymAction lSymAction = new SymAction();
    exitItem.addActionListener(lSymAction);
    Help.addActionListener(lSymAction);
    about.addActionListener(lSymAction);
		ShutButton.addActionListener(lSymAction);
		KillButton.addActionListener(lSymAction);
		//}}
  }

    /**
     * Creates a new instance of JFrame1 with the given title.
     * @param sTitle the title for the new frame.
     * @see #JFrame1()
     */
  public TyShutdown(String sTitle)
  {
    this();
    setTitle(sTitle);
  }
  
  /**
   * The entry point for this application.
   * Sets the Look and Feel to the System Look and Feel.
   * Creates a new JFrame1 and makes it visible.
   */
  static public void main(String args[])
  {
    try {
        // Add the following code if you want the Look and Feel
        // to be set to the Look and Feel of the native system.
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (Exception e) { 
        }
        

      //Create a new instance of our application's frame, and make it visible.
      (new TyShutdown()).setVisible(true);
    } 
    catch (Throwable t) {
      t.printStackTrace();
      //Ensure the application exits with an error condition.
      System.exit(1);
    }
  }

    /**
     * Notifies this component that it has been added to a container
     * This method should be called by <code>Container.add</code>, and 
     * not by user code directly.
     * Overridden here to adjust the size of the frame if needed.
     * @see java.awt.Container#removeNotify
     */
  public void addNotify()
  {
    // Record the size of the window prior to calling parents addNotify.
    Dimension size = getSize();
    
    super.addNotify();
    
    if (frameSizeAdjusted)
      return;
    frameSizeAdjusted = true;
    
    // Adjust size of frame according to the insets and menu bar
    javax.swing.JMenuBar menuBar = getRootPane().getJMenuBar();
    int menuBarHeight = 0;
    if (menuBar != null)
        menuBarHeight = menuBar.getPreferredSize().height;
    Insets insets = getInsets();
    setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height + menuBarHeight);
  }

  // Used by addNotify
  boolean frameSizeAdjusted = false;

  //{{DECLARE_CONTROLS
	javax.swing.JButton ShutButton = new javax.swing.JButton();
	javax.swing.JLabel Msg = new javax.swing.JLabel();
	javax.swing.JMenuBar JMenuBar1 = new javax.swing.JMenuBar();
	javax.swing.JMenu fileMenu = new javax.swing.JMenu();
	javax.swing.JMenuItem exitItem = new javax.swing.JMenuItem();
	javax.swing.JSeparator JSeparator1 = new javax.swing.JSeparator();
	javax.swing.JMenu helpMenu = new javax.swing.JMenu();
	javax.swing.JMenuItem Help = new javax.swing.JMenuItem();
	javax.swing.JMenuItem about = new javax.swing.JMenuItem();
	javax.swing.JButton KillButton = new javax.swing.JButton();
	//}}

	TyShutBean2 TyShutBean21 = null;
	TymeacInterface Ti = null;	

  //{{DECLARE_MENUS
	//}}

  void exitApplication()
  {    
    this.setVisible(false);    // hide the Frame
    this.dispose();            // free the system resources
    if  (Ti == null) {
				System.exit(0);   // close the application 
    } // endif
  }

  class SymWindow extends java.awt.event.WindowAdapter
  {
    public void windowClosing(java.awt.event.WindowEvent event)
    {
      Object object = event.getSource();
      if (object == TyShutdown.this)
        TyShutdown_windowClosing(event);
    }
  }

  void TyShutdown_windowClosing(java.awt.event.WindowEvent event)
  {
    // to do: code goes here.
       
    TyShutdown_windowClosing_Interaction1(event);
  }

  void TyShutdown_windowClosing_Interaction1(java.awt.event.WindowEvent event) {
    try {
      this.exitApplication();
    } catch (Exception e) {
    }
  }

  class SymAction implements java.awt.event.ActionListener
  {
    public void actionPerformed(java.awt.event.ActionEvent event)
    { 
      Object object = event.getSource();
      if (object == exitItem)
        exitItem_actionPerformed(event);
      else if (object == Help)
        Help_actionPerformed(event);
      else  if (object == about)
        about_actionPerformed(event);
			else if (object == ShutButton)
				ShutButton_actionPerformed(event);
			else if (object == KillButton)
				KillButton_actionPerformed(event);          
      
    }
  }

  void exitItem_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    exitItem_actionPerformed_Interaction1(event);
  }

  void exitItem_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
    try {
      this.exitApplication();
    } catch (Exception e) {
    }
  }

  void Help_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    Help_actionPerformed_Interaction1(event);
  }

  void Help_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
    
    TyHelp th = new TyHelp();

    th.putOut(tyShutdownBundle.getString("th_putOut"));
    
  } 
    
   void about_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    about_actionPerformed_Interaction1(event);
  }

  void about_actionPerformed_Interaction1(java.awt.event.ActionEvent event) { 
  
    try {
      // TymeacAbout Create with owner and show as modal
      {
        TyAbout TyAbout1 = new TyAbout(this);
        TyAbout1.setModal(true);
        TyAbout1.setVisible(true);
      }
    } catch (Exception e) {
    }
  }

	void ShutButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		ShutButton_actionPerformed_Interaction1(event);
	}

	void ShutButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
			// When no obj
			if  (TyShutBean21 == null) {
	
					// When internal
          if  (Ti != null) {

              // get the obj
              TyShutBean21 = new TyShutBean2(Ti);
          }
          else {
          		 // get the obj
            	 TyShutBean21 = new TyShutBean2();

          } // endif
			} // endif

			// do function
			TyShutBean21.shutButton();

			// what came back
			Msg.setText(tyShutdownBundle.getString("Msg_text_1") + TyShutBean21.getShutData());					 
			

		} catch (java.lang.Exception e) {
		}
	}
	static java.util.ResourceBundle tyShutdownBundle = java.util.ResourceBundle.getBundle("com.tymeac.client.jframe.TyShutdownBundle");

	void KillButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		KillButton_actionPerformed_Interaction1(event);
	}

	void KillButton_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
			// When no obj
			if  (TyShutBean21 == null) {
	
					// When internal
          if  (Ti != null) {

              // get the obj
              TyShutBean21 = new TyShutBean2(Ti);
          }
          else {
          		 // get the obj
            	 TyShutBean21 = new TyShutBean2();

          } // endif
			} // endif

			// do function
			TyShutBean21.killButton();

			// what came back
			Msg.setText(tyShutdownBundle.getString("Msg_text_1") + TyShutBean21.getShutData());					 
			

		} catch (java.lang.Exception e) {
		}
	}
}
