package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyStatsBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyStats_title", "Tymeac On Request Statistics"},
		{"StatsButton_text", "Write Statistics"},
		{"StatsButton_actionCommand", "Write Statistics"},
		{"StatsButton_toolTipText", ""},
		{"Msg_text", " Press Button "},
		{"Msg_toolTipText", ""},
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"th_putOut", "TyStats.html"},
		{"case_0__Msg_text", " Connection failure"},
		{"case_1__Msg_text", " Tymeac shutting down"},
		{"case_2__Msg_text", " A Statistics Repository is not available"},
		{"case_3__Msg_text", " DBMS or local file Error"},
		{"case_4__Msg_text", " Current statistics were written"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
