package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyStalledBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyStalled_title", "Tymeac Stalled Asynchronous Requests"},
		{"Msg_text", " Press Refresh"},
		{"Msg_toolTipText", ""},
		{"StalledLabel_text", "reason  (ID)             Entered                                         Function Name"},
		{"StalledLabel_toolTipText", ""},
		{"DetailLabel_text", "Queue\'s not responding"},
		{"DetailLabel_toolTipText", ""},
		{"RefreshButton_text", "Refresh"},
		{"RefreshButton_actionCommand", "Refresh"},
		{"RefreshButton_toolTipText", "Refresh the Stalled List"},
		{"ReSchdButton_text", "Re-Schd OA"},
		{"ReSchdButton_actionCommand", "Re-Schd OA"},
		{"ReSchdButton_toolTipText", "Reschedule an Output Agent Queue"},
		{"PurgeButton_text", "Purge"},
		{"PurgeButton_actionCommand", "Purge"},
		{"PurgeButton_toolTipText", "Purge selected requests"},
		{"DetailButton_text", "Details"},
		{"DetailButton_actionCommand", "Details"},
		{"DetailButton_toolTipText", "Queue\'s not responding"},
		{"StalledPane_toolTipText", ""},
		{"StalledList_toolTipText", ""},
		{"DetailPane_toolTipText", ""},
		{"DetailList_toolTipText", ""},
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"th_putOut", "TyStalled.html"},
		{"case_0__Msg_text", " Connection failure"},
		{"case_2__Msg_text", " No requests are stalled"},
		{"case_3__Msg_text", " Make a selection"},
		{"case_0__Msg_text_1", " Make a Selection"},
		{"case_1__Msg_text", " Selected item no longer stalled"},
		{"case_2__Msg_text_1", " Selected item is not an Output Agent"},
		{"case_3__Msg_text_1", " All normal Queues have not finished"},
		{"case_4__Msg_text", " Output Agent is a bad Queue"},
		{"case_5__Msg_text", " Output Agent is already scheduled"},
		{"case_6__Msg_text", " Nothing selected"},
		{"case_7__Msg_text", " Selected item was not found"},
		{"case_8__Msg_text", " Invalid ID on selected item"},
		{"case_9__Msg_text", " No prior Refresh"},
		{"case_10__Msg_text", " Communication error"},
		{"case_11__Msg_text", " No Requests Stalled"},
		{"default__Msg_text", " Scheduling failed with return code=("},
		{"TokenString", ")"},
		{"case_0__Msg_text_2", " Connection failure"},
		{"case_2__Msg_text_2", " Make a selection"},
		{"case_3__Msg_text_2", " Selected item[s] no longer active"},
		{"case_4__Msg_text_1", " No requests are stalled"},
		{"case_5__Msg_text_1", " Use Refresh Button First"},
		{"case_0__Msg_text_3", " Connection failure"},
		{"case_1__Msg_text_1", " Nothing selected"},
		{"case_2__Msg_text_3", " Selected item is no longer active"},
		{"case_3__Msg_text_3", " Make a selection"},
		{"case_4__Msg_text_2", " Use Refresh Button First"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
