package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

import java.awt.*;
import javax.swing.*;
import com.tymeac.base.*;

/**
 * The Statistics display frame.
 */
public class TyStats extends javax.swing.JFrame
{
  private static final long serialVersionUID = 1L;

  // Used by addNotify
  boolean frameSizeAdjusted = false;

  //{{DECLARE_CONTROLS
	javax.swing.JButton StatsButton = new javax.swing.JButton();
	javax.swing.JLabel Msg = new javax.swing.JLabel();
	javax.swing.JMenuBar JMenuBar1 = new javax.swing.JMenuBar();
	javax.swing.JMenu fileMenu = new javax.swing.JMenu();
	javax.swing.JMenuItem exitItem = new javax.swing.JMenuItem();
	javax.swing.JSeparator JSeparator1 = new javax.swing.JSeparator();
	javax.swing.JMenu helpMenu = new javax.swing.JMenu();
	javax.swing.JMenuItem Help = new javax.swing.JMenuItem();
	javax.swing.JMenuItem about = new javax.swing.JMenuItem();
	//}}

	TyStatsBean TyStatsBean21 = null;
  TymeacInterface Ti = null;


  class SymWindow extends java.awt.event.WindowAdapter
  {
    public void windowClosing(java.awt.event.WindowEvent event)
    {
      Object object = event.getSource();
      if (object == TyStats.this)
        TyStats_windowClosing(event);
    }
  }

  class SymAction implements java.awt.event.ActionListener
  {
    public void actionPerformed(java.awt.event.ActionEvent event)
    { 
      Object object = event.getSource();
      if (object == exitItem)
        exitItem_actionPerformed(event);
      else if (object == Help)
        Help_actionPerformed(event);
      else  if (object == about)
        about_actionPerformed(event);
			else if (object == StatsButton)
				StatsButton_actionPerformed(event);     
      
    }
  }

	static java.util.ResourceBundle tyStatsBundle = java.util.ResourceBundle.getBundle("com.tymeac.client.jframe.TyStatsBundle");
  public TyStats()
  {
    // This code is automatically generated by Visual Cafe when you add
    // components to the visual environment. It instantiates and initializes
    // the components. To modify the code, only use code syntax that matches
    // what Visual Cafe can generate, or Visual Cafe may be unable to back
    // parse your Java file into its visual environment.
    //{{INIT_CONTROLS
    setJMenuBar(JMenuBar1);
    setTitle(tyStatsBundle.getString("TyStats_title"));
    setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    getContentPane().setLayout(null);
    setSize(439,150);
		setVisible(false);
    //$$ JMenuBar1.move(168,312);
    fileMenu.setText(tyStatsBundle.getString("fileMenu_text"));
    fileMenu.setActionCommand(tyStatsBundle.getString("fileMenu_actionCommand"));
		fileMenu.setToolTipText(tyStatsBundle.getString("fileMenu_toolTipText").length() != 0 ? tyStatsBundle.getString("fileMenu_toolTipText") : null);
    fileMenu.setMnemonic((int)'F');
    JMenuBar1.add(fileMenu);
    
    fileMenu.add(JSeparator1);
    
    exitItem.setText(tyStatsBundle.getString("exitItem_text"));
    exitItem.setActionCommand(tyStatsBundle.getString("exitItem_actionCommand"));
		exitItem.setToolTipText(tyStatsBundle.getString("exitItem_toolTipText").length() != 0 ? tyStatsBundle.getString("exitItem_toolTipText") : null);
    exitItem.setMnemonic((int)'X');
    fileMenu.add(exitItem);
		JSeparator1.setToolTipText(tyStatsBundle.getString("JSeparator1_toolTipText").length() != 0 ? tyStatsBundle.getString("JSeparator1_toolTipText") : null);
    
    helpMenu.setText(tyStatsBundle.getString("helpMenu_text"));
    helpMenu.setActionCommand(tyStatsBundle.getString("helpMenu_actionCommand"));
		helpMenu.setToolTipText(tyStatsBundle.getString("helpMenu_toolTipText").length() != 0 ? tyStatsBundle.getString("helpMenu_toolTipText") : null);
    helpMenu.setMnemonic((int)'H');
    JMenuBar1.add(helpMenu);
    
    fileMenu.add(JSeparator1);
       
    Help.setText(tyStatsBundle.getString("Help_text"));
    Help.setActionCommand(tyStatsBundle.getString("Help_actionCommand"));
		Help.setToolTipText(tyStatsBundle.getString("Help_toolTipText").length() != 0 ? tyStatsBundle.getString("Help_toolTipText") : null);
    Help.setMnemonic((int)'D');
    helpMenu.add(Help);
    
    fileMenu.add(JSeparator1);
    
    about.setText(tyStatsBundle.getString("about_text"));
    about.setActionCommand(tyStatsBundle.getString("about_actionCommand"));
		about.setToolTipText(tyStatsBundle.getString("about_toolTipText").length() != 0 ? tyStatsBundle.getString("about_toolTipText") : null);
    about.setMnemonic((int)'A');
    helpMenu.add(about); 

		StatsButton.setText(tyStatsBundle.getString("StatsButton_text"));
		StatsButton.setActionCommand(tyStatsBundle.getString("StatsButton_actionCommand"));
		StatsButton.setToolTipText(tyStatsBundle.getString("StatsButton_toolTipText").length() != 0 ? tyStatsBundle.getString("StatsButton_toolTipText") : null);
		getContentPane().add(StatsButton);
		StatsButton.setBounds(144,36,132,36);
		Msg.setText(tyStatsBundle.getString("Msg_text"));
		Msg.setToolTipText(tyStatsBundle.getString("Msg_toolTipText").length() != 0 ? tyStatsBundle.getString("Msg_toolTipText") : null);
		getContentPane().add(Msg);
		Msg.setForeground(new java.awt.Color(128,0,0));
		Msg.setFont(new Font("Dialog", Font.PLAIN, 12));
		Msg.setBounds(20,100,390,30);
		JMenuBar1.setToolTipText(tyStatsBundle.getString("JMenuBar1_toolTipText").length() != 0 ? tyStatsBundle.getString("JMenuBar1_toolTipText") : null);
    //}}

		Msg.setBorder(new javax.swing.border.EtchedBorder());

    //{{INIT_MENUS
    //}}

    //{{REGISTER_LISTENERS
    SymWindow aSymWindow = new SymWindow();
    this.addWindowListener(aSymWindow);
    
    SymAction lSymAction = new SymAction();
    exitItem.addActionListener(lSymAction);
    Help.addActionListener(lSymAction);
    about.addActionListener(lSymAction);
		StatsButton.addActionListener(lSymAction);
    //}}
  }
    public TyStats(TymeacInterface TyI)
    {
			this();
    	Ti = TyI;

    	try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (Exception e) { 
        }
    }
    /**
     * Creates a new instance of JFrame1 with the given title.
     * @param sTitle the title for the new frame.
     */
  public TyStats(String sTitle)
  {
    this();
    setTitle(sTitle);
  }
   void about_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    about_actionPerformed_Interaction1(event);
  }
  void about_actionPerformed_Interaction1(java.awt.event.ActionEvent event) { 
  
    try {
      // TymeacAbout Create with owner and show as modal
      {
        TyAbout TyAbout1 = new TyAbout(this);
        TyAbout1.setModal(true);
        TyAbout1.setVisible(true);
      }
    } catch (Exception e) {
    }
  }
    /**
     * Notifies this component that it has been added to a container
     * This method should be called by <code>Container.add</code>, and 
     * not by user code directly.
     * Overridden here to adjust the size of the frame if needed.
     * @see java.awt.Container#removeNotify
     */
  public void addNotify()
  {
    // Record the size of the window prior to calling parents addNotify.
    Dimension size = getSize();
    
    super.addNotify();
    
    if (frameSizeAdjusted)
      return;
    frameSizeAdjusted = true;
    
    // Adjust size of frame according to the insets and menu bar
    javax.swing.JMenuBar menuBar = getRootPane().getJMenuBar();
    int menuBarHeight = 0;
    if (menuBar != null)
        menuBarHeight = menuBar.getPreferredSize().height;
    Insets insets = getInsets();
    setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height + menuBarHeight);
  }
  //{{DECLARE_MENUS
	//}}

  void exitApplication()
  {    
    this.setVisible(false);    // hide the Frame
    this.dispose();            // free the system resources
		if  (Ti == null) {
    	  System.exit(0);   // close the application 
		} // endif    
  }
  void exitItem_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    exitItem_actionPerformed_Interaction1(event);
  }
  void exitItem_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
    try {
      this.exitApplication();
    } catch (Exception e) {
    }
  }
  void Help_actionPerformed(java.awt.event.ActionEvent event)
  {
    // to do: code goes here.
       
    Help_actionPerformed_Interaction1(event);
  }
  void Help_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
    
    TyHelp th = new TyHelp();

    th.putOut(tyStatsBundle.getString("th_putOut"));
    
  }
  /**
   * The entry point for this application.
   * Sets the Look and Feel to the System Look and Feel.
   * Creates a new JFrame1 and makes it visible.
   */
  static public void main(String args[])
  {
    try {
        // Add the following code if you want the Look and Feel
        // to be set to the Look and Feel of the native system.
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (Exception e) { 
        }
        

      //Create a new instance of our application's frame, and make it visible.
      (new TyStats()).setVisible(true);
    } 
    catch (Throwable t) {
      t.printStackTrace();
      //Ensure the application exits with an error condition.
      System.exit(1);
    }
  }
	void StatsButton_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
		// When internal
    if  (Ti != null) {

       	// get the obj
       	TyStatsBean21 = new TyStatsBean(Ti);
    }
    else {
      	// get the obj
      	TyStatsBean21 = new TyStatsBean();

    } // endif	

		// do the write
		TyStatsBean21.writeButton();
    
    // the result of this:
    switch (TyStatsBean21.getGetResult()) {
                  
        case 0: Msg.setText(tyStatsBundle.getString("case_0__Msg_text"));
                  break;                    
            
        case 1: Msg.setText(tyStatsBundle.getString("case_1__Msg_text")); 
                  break;
                  
        case 2: Msg.setText(tyStatsBundle.getString("case_2__Msg_text")); 
                  break;
        
        case 3: Msg.setText(tyStatsBundle.getString("case_3__Msg_text")); 
                  break;
        
        case 4: Msg.setText(tyStatsBundle.getString("case_4__Msg_text")); 
                  break;
                                    
    } // end-switch  			 
	}
  void TyStats_windowClosing(java.awt.event.WindowEvent event)
  {
    // to do: code goes here.
       
    TyStats_windowClosing_Interaction1(event);
  }
  void TyStats_windowClosing_Interaction1(java.awt.event.WindowEvent event) {
    try {
      this.exitApplication();
    } catch (Exception e) {
    }
  }
}
