package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyUserFunctionsBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyUserFunctions_title", "Tymeac User Function Class Maintenance"},
		{"FunctionText_text", ""},
		{"FunctionText_toolTipText", "Enter a Tymeac Function Name"},
		{"ImportButton_text", "Import"},
		{"ImportButton_actionCommand", "Import"},
		{"ImportButton_toolTipText", "Load an existing Function"},
		{"DeleteButton_text", "Delete"},
		{"DeleteButton_actionCommand", "Delete"},
		{"DeleteButton_toolTipText", "Delete this Function"},
		{"AddButton_text", "Add"},
		{"AddButton_actionCommand", "Add"},
		{"AddButton_toolTipText", "Add this Queue to List"},
		{"RemoveButton_text", "Remove"},
		{"RemoveButton_actionCommand", "Remove"},
		{"RemoveButton_toolTipText", "Remove Selected Queue from List"},
		{"FinishButton_text", "Finish"},
		{"FinishButton_actionCommand", "Finish"},
		{"FinishButton_toolTipText", "Add/Update this Function"},
		{"FunctionLabel_text", "Function Name"},
		{"FunctionLabel_toolTipText", ""},
		{"OALabel_text", "Output Agent Queue (optional)"},
		{"OALabel_toolTipText", ""},
		{"OAText_text", ""},
		{"OAText_toolTipText", ""},
		{"AddLabel_text", "Queue Name to Add"},
		{"AddLabel_toolTipText", ""},
		{"AddText_text", ""},
		{"AddText_toolTipText", ""},
		{"ListLabel_text", "Queue List"},
		{"ListLabel_toolTipText", ""},
		{"ListScrollPane_toolTipText", "List of Queues for this Function"},
		{"TheList_toolTipText", ""},
		{"Msg_text", " Enter a Function Name"},
		{"Msg_toolTipText", ""},
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		{"ReadJavaFile_title", "Open"},
		{"ReadJavaFile_directory", ""},
		{"ReadJavaFile_file", "TymeacUserFunctions.java"},
		{"SaveJavaFile_title", "Save"},
		{"SaveJavaFile_directory", ""},
		{"SaveJavaFile_file", "TymeacUserFunctions.java"},
		//}}End Automatic Code Generation Block
		{"th_putOut", "TyUserFuncMaint.html"},
		{"Msg_text_1", "Enter a Queue to Add"},
		{"AddText_text_1", ""},
		{"Msg_text_2", " OK"},
		{"Msg_text_3", " OK"},
		{"Msg_text_4", " OK"},
		{"Msg_text_5", " Enter a Function name to Import"},
		{"Msg_text_6", " No file to import"},
		{"case_0__Msg_text", " OK"},
		{"Msg_text_7", " Function does not exist"},
		{"Msg_text_8", " File structure error"},
		{"Msg_text_9", " File read or close error"},
		{"Msg_text_10", " Enter a Function name to Delete"},
		{"Msg_text_11", " No file to delete"},
		{"case_0__Msg_text_1", " Function \'"},
		{"deleted", "\' deleted"},
		{"FunctionText_text_1", ""},
		{"OAText_text_1", ""},
		{"Msg_text_12", " Function does not exist"},
		{"Msg_text_13", " Delete error"},
		{"Msg_text_14", " Enter a Function name to Add"},
		{"Msg_text_15", " No file to save"},
		{"case_0__Msg_text_2", " OK"},
		{"Msg_text_16", " Adding function already exists"},
		{"Msg_text_17", " Cannot change Function for update"},
		{"Msg_text_18", " There are no Queues for this Function"},
		{"Msg_text_19", " A file error occurred"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
