package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyUserVariablesBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyUserVariables_title", "Tymeac User Variables Set Up"},
		{"TabbedPane_toolTipText", ""},
		{"GeneralPanel_toolTipText", ""},
		{"MonLabel_text", "Monitor interval in seconds"},
		{"MonLabel_toolTipText", ""},
		{"monText_text", ""},
		{"monText_toolTipText", "60 recomended"},
		{"actText_text", ""},
		{"actText_toolTipText", "Minutes, not seconds"},
		{"ActLabel_text", "Inactivation time in minutes"},
		{"ActLabel_toolTipText", ""},
		{"notifyText_text", ""},
		{"notifyText_toolTipText", "Tymeac Function to notify when a problem"},
		{"NotifyLabel_text", "Notification Function"},
		{"NotifyLabel_toolTipText", ""},
		{"ImportButton_text", "Import"},
		{"ImportButton_actionCommand", "Import"},
		{"ImportButton_toolTipText", "Import an existing file"},
		{"FinishButton_text", "Finish"},
		{"FinishButton_actionCommand", "Finish"},
		{"FinishButton_toolTipText", "Update/Write File"},
		{"SysExit_text", "   System.Exit(0) at Shut Down"},
		{"SysExit_actionCommand", "   System.Exit(0) at Shut Down"},
		{"SysExit_toolTipText", ""},
    
    {"SecurityPanel_toolTipText", ""},
    {"LoginContextText_text", ""},
    {"LoginContextText_toolTipText", "Security Login Context"},
    {"LoginContextLabel_text", "Login Context"},
    {"LoginContextLabel_toolTipText", ""},
    
    
		{"ExitsPanel_toolTipText", ""},
		{"StartupScrollPane_toolTipText", ""},
		{"StartupList_toolTipText", ""},
		{"Shut1ScrollPane_toolTipText", ""},
		{"Shut1List_toolTipText", ""},
		{"Shut2ScrollPane_toolTipText", ""},
		{"Shut2List_toolTipText", ""},
		{"StartupLabel_text", "Startup Classes"},
		{"StartupLabel_toolTipText", ""},
		{"Shut1Label_text", "Shutdown Stage1 Classes"},
		{"Shut1Label_toolTipText", ""},
		{"Shut2Label_text", "Shutdown Stage2 Classes"},
		{"Shut2Label_toolTipText", ""},
		{"StartupText_text", ""},
		{"StartupText_toolTipText", ""},
		{"Shut1Text_text", ""},
		{"Shut1Text_toolTipText", ""},
		{"Shut2Text_text", ""},
		{"Shut2Text_toolTipText", ""},
		{"StartupAddButton_text", "Add"},
		{"StartupAddButton_actionCommand", "Add"},
		{"StartupAddButton_toolTipText", "Add TextField to List"},
		{"StartupRemoveButton_text", "Remove"},
		{"StartupRemoveButton_actionCommand", "Remove"},
		{"StartupRemoveButton_toolTipText", "Remove Selected Item from List"},
		{"Shut1AddButton_text", "Add"},
		{"Shut1AddButton_actionCommand", "Add"},
		{"Shut1AddButton_toolTipText", "Add TextField to List"},
		{"Shut1RemoveButton_text", "Remove"},
		{"Shut1RemoveButton_actionCommand", "Remove"},
		{"Shut1RemoveButton_toolTipText", "Remove Selected Item from List"},
		{"Shut2AddButton_text", "Add"},
		{"Shut2AddButton_actionCommand", "Add"},
		{"Shut2AddButton_toolTipText", "Add TextField to List"},
		{"Shut2RemoveButton_text", "Remove"},
		{"Shut2RemoveButton_actionCommand", "Remove"},
		{"Shut2RemoveButton_toolTipText", "Remove Selected Item form List"},
		{"StartupFuncLabel_text", "Startup Functions"},
		{"StartupFuncLabel_toolTipText", ""},
		{"StartupFuncScrollPane_toolTipText", ""},
		{"StartupFuncList_toolTipText", ""},
		{"StartupFuncText_text", ""},
		{"StartupFuncText_toolTipText", ""},
		{"StartupAddFuncButton_text", "Add"},
		{"StartupAddFuncButton_actionCommand", "Add"},
		{"StartupAddFuncButton_toolTipText", "Add TextField to List"},
		{"StartupRemoveFuncButton_text", "Remove"},
		{"StartupRemoveFuncButton_actionCommand", "Remove"},
		{"StartupRemoveFuncButton_toolTipText", "Remove Selected Item from List"},
		{"AltPanel_toolTipText", ""},
		{"HeaderLabel_text", "***  Alternative Files  ***"},
		{"HeaderLabel_toolTipText", ""},
		{"statsDirText_text", ""},
		{"statsDirText_toolTipText", ""},
		{"statsFileText_text", ""},
		{"statsFileText_toolTipText", ""},
		{"logDirText_text", ""},
		{"logDirText_toolTipText", ""},
		{"logFileText_text", ""},
		{"logFileText_toolTipText", ""},
		{"StatsDirLabel_text", " Statistics Directory"},
		{"StatsDirLabel_toolTipText", ""},
		{"StatsFileLabel_text", " Statistics File Name"},
		{"StatsFileLabel_toolTipText", ""},
		{"LogDirLabel_text", " Log Directory"},
		{"LogDirLabel_toolTipText", ""},
		{"LogFileLabel_text", " Log File Name"},
		{"LogFileLabel_toolTipText", ""},
		{"AltLabel_text", "***  Alternative Classes  ***"},
		{"AltLabel_toolTipText", ""},
		{"statsAltText_text", ""},
		{"statsAltText_toolTipText", ""},
		{"logAltText_text", ""},
		{"logAltText_toolTipText", ""},
		{"StatsAltLabel_text", " Statistics Class"},
		{"StatsAltLabel_toolTipText", ""},
		{"LogAltLabel_text", " Log Class"},
		{"LogAltLabel_toolTipText", ""},
		{"TabbedPane_titleAt0", "General"},
    {"TabbedPane_titleAt1", "Security"},
		{"TabbedPane_titleAt2", "Exits"},
		{"TabbedPane_titleAt3", "Alternate"},
    
		{"ReadJavaFile_title", "Open"},
		{"ReadJavaFile_directory", ""},
		{"ReadJavaFile_file", "TymeacUserVariables.java"},
		{"WriteJavaFile_title", "Save"},
		{"WriteJavaFile_directory", ""},
		{"WriteJavaFile_file", "TymeacUserVariaibles.java"},
		{"JScrollPane1_toolTipText", ""},
		{"JScrollPane2_toolTipText", ""},
		{"JScrollPane3_toolTipText", ""},
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"th_putOut", "TyUserVariables.html"},
		{"StartupText_text_1", ""},
		{"Shut1Text_text_1", ""},
		{"Shut2Text_text_1", ""},
		{"StartupFuncText_text_1", ""},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
