package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyVariablesBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyVariables_title", "Tymeac Start Up Variables"},
		{"TabbedPane_toolTipText", ""},
		{"BasicPanel_toolTipText", ""},
		{"rmiURLText_text", ""},
		{"rmiURLText_toolTipText", "Minutes, not seconds"},
		{"RMIURLLabel_text", "URL"},
		{"RMIURLLabel_toolTipText", ""},
		{"rmiAssocText_text", ""},
		{"rmiAssocText_toolTipText", "Tymeac Function to notify when a problem"},
		{"RMIAssocLabel_text", "Associated Name"},
		{"RMIAssocLabel_toolTipText", ""},
		{"ImportBasicButton_text", "Import"},
		{"ImportBasicButton_actionCommand", "Import"},
		{"ImportBasicButton_toolTipText", "Import an existing file"},
		{"FinishBasicButton_text", "Finish"},
		{"FinishBasicButton_actionCommand", "Finish"},
		{"FinishBasicButton_toolTipText", "Update/Write File"},
		{"BasicMsg_text", ""},
		{"BasicMsg_toolTipText", ""},
		{"IIOPPanel_toolTipText", ""},
		{"iiopLabel_text", " IIOP Server Name"},
		{"iiopLabel_toolTipText", ""},
		{"IIOPText_text", ""},
		{"IIOPText_toolTipText", ""},
		{"ImportIIOPButton_text", "Import"},
		{"ImportIIOPButton_actionCommand", "Import"},
		{"ImportIIOPButton_toolTipText", ""},
		{"FinishIIOPButton_text", "Finish"},
		{"FinishIIOPButton_actionCommand", "Finish"},
		{"FinishIIOPButton_toolTipText", ""},
		{"iiopMsg_text", ""},
		{"iiopMsg_toolTipText", ""},
		{"AltPanel_toolTipText", ""},
		{"AltText_text", ""},
		{"AltText_toolTipText", ""},
		{"AltLabel_text", " Alternate Class::URL"},
		{"AltLabel_toolTipText", ""},
		{"AltImportButton_text", "Import"},
		{"AltImportButton_actionCommand", "Import"},
		{"AltImportButton_toolTipText", ""},
		{"AltFinishButton_text", "Finsih"},
		{"AltFinishButton_actionCommand", "Finsih"},
		{"AltFinishButton_toolTipText", ""},
		{"AltMsg_text", ""},
		{"AltMsg_toolTipText", ""},
		{"TabbedPane_titleAt0", "Basic RMI"},
		{"TabbedPane_titleAt1", "IIOP"},
		{"TabbedPane_titleAt2", "Alternate"},
		{"ReadJavaFile_title", "Open"},
		{"ReadJavaFile_directory", ""},
		{"ReadJavaFile_file", "TyVariables.java"},
		{"WriteJavaFile_title", "Save"},
		{"WriteJavaFile_directory", ""},
		{"WriteJavaFile_file", "TyVariaibles.java"},
		{"JScrollPane1_toolTipText", ""},
		{"JScrollPane2_toolTipText", ""},
		{"JScrollPane3_toolTipText", ""},
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"th_putOut", "TyVariables.html"},
		{"case_0__BasicMsg_text", " OK"},
		{"case_1__BasicMsg_text", " There is no basic data"},
		{"case_100__BasicMsg_text", " File open error"},
		{"case_200__BasicMsg_text", " File read error"},
		{"case_300__BasicMsg_text", " File close error"},
		{"default__BasicMsg_text", " File is formatted incorrectly"},
		{"case_0__BasicMsg_text_1", " OK"},
		{"case_1__BasicMsg_text_1", " URL missing"},
		{"case_2__BasicMsg_text", " Tymeac name misssing"},
		{"case_1001__BasicMsg_text", " File open error"},
		{"case_1002__BasicMsg_text", " File write error"},
		{"case_1003__BasicMsg_text", " File close error"},
		{"case_0__iiopMsg_text", " OK"},
		{"case_1__iiopMsg_text", " There is no IIOP data"},
		{"case_100__iiopMsg_text", " File open error"},
		{"case_200__iiopMsg_text", " File read error"},
		{"case_300__iiopMsg_text", " File close error"},
		{"default__iiopMsg_text", " File is formatted incorrectly"},
		{"case_0__iiopMsg_text_1", " OK"},
		{"case_1__iiopMsg_text_1", " IIOP name missing"},
		{"case_1001__iiopMsg_text", " File open error"},
		{"case_1002__iiopMsg_text", " File write error"},
		{"case_1003__iiopMsg_text", " File close error"},
		{"case_0__AltMsg_text", " OK"},
		{"case_1__AltMsg_text", " There is no alternate class data"},
		{"case_100__AltMsg_text", " File open error"},
		{"case_200__AltMsg_text", " File read error"},
		{"case_300__AltMsg_text", " File close error"},
		{"default__AltMsg_text", " File is formatted incorrectly"},
		{"case_0__AltMsg_text_1", " OK"},
		{"case_1__AltMsg_text_1", " Alternate class name missing"},
		{"case_1001__AltMsg_text", " File open error"},
		{"case_1002__AltMsg_text", " File write error"},
		{"case_1003__AltMsg_text", " File close error"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
