package com.tymeac.client.jframe;

/* 
 * Copyright (c) 1998 - 2004 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyWlDataBundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyWlData_title", "Tymeac Queue Wait Lists data"},
		{"QueText_text", ""},
		{"QueText_toolTipText", "Enter a Queue name"},
		{"QueLabel_text", "Queue Name"},
		{"QueLabel_toolTipText", ""},
		{"RefreshButton_text", "Refresh"},
		{"RefreshButton_actionCommand", "Refresh"},
		{"RefreshButton_toolTipText", "Refresh the Lists"},
		{"Msg_text", " Enter a Queue Name"},
		{"Msg_toolTipText", ""},
		{"UsePane_toolTipText", ""},
		{"UseList_toolTipText", ""},
		{"UsedPanel_toolTipText", ""},
		{"UsedList_toolTipText", ""},
    {"HiUsedPanel_toolTipText", ""},
    {"HiUsedList_toolTipText", ""},
		{"ResetPane_toolTipText", ""},
		{"ResetList_toolTipText", ""},
		{"PriPane_toolTipText", ""},
		{"PriList_toolTipText", ""},
		{"SecPane_toolTipText", ""},
		{"SecList_toolTipText", ""},
		{"UseLabel_text", "       use                       used                        used                       reset                      pri                           sec"},
		{"UseLabel_toolTipText", ""},
		{"InLabel_text", "        In                        Times                       High                       Times                      Over                       Over"},
		{"InLabel_toolTipText", ""},
		{"JMenuBar1_toolTipText", ""},
		{"fileMenu_text", "File"},
		{"fileMenu_actionCommand", "File"},
		{"fileMenu_toolTipText", ""},
		{"exitItem_text", "Exit"},
		{"exitItem_actionCommand", "Exit"},
		{"exitItem_toolTipText", ""},
		{"JSeparator1_toolTipText", ""},
		{"helpMenu_text", "Help"},
		{"helpMenu_actionCommand", "Help"},
		{"helpMenu_toolTipText", ""},
		{"Help_text", "Document"},
		{"Help_actionCommand", "Doc..."},
		{"Help_toolTipText", ""},
		{"about_text", "About..."},
		{"about_actionCommand", "About..."},
		{"about_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"th_putOut", "TyWlData.html"},
		{"Msg_text_1", " Enter a Queue Name first"},
		{"case_0__Msg_text", " Connection failure"},
		{"case_1__Msg_text", " Tymeac shutting down"},
		{"case_2__Msg_text", " Invalid Queue Name"},
		{"case_3__Msg_text", " Refresh when ready"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
