// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.tymeac.demo;

public final class TyDemoClientCancel2Impl_Stub
    extends java.rmi.server.RemoteStub
    implements com.tymeac.base.InterruptionReady
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_ready_0;
    
    static {
	try {
	    $method_ready_0 = com.tymeac.base.InterruptionReady.class.getMethod("ready", new java.lang.Class[] {com.tymeac.base.CancelParm.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public TyDemoClientCancel2Impl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of ready(CancelParm)
    public void ready(com.tymeac.base.CancelParm $param_CancelParm_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_ready_0, new java.lang.Object[] {$param_CancelParm_1}, -7127141853298948857L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
