package com.tymeac.common;
// DO NOT EDIT THIS FILE
  
public class TyVariables {
  private static final boolean tymeac_use_rmi       = true;
  private static final boolean tymeac_use_iiop      = false;
  private static final boolean tymeac_use_alternate = false;
  private static final String  tymeac_url_name      = "rmi:///";
  private static final String  tymeac_name          = "com.tymeac.demo.TyDemoActivation";
  private static final String  tymeac_iiop_name     = null;
  private static final String  tymeac_alternate_class_name = null;
  
public String getAltName() { 
   return tymeac_alternate_class_name;
} // end-method
  
public String getIIOPName ( ) { 
  return tymeac_iiop_name;
} // end-method	
  
public String getTymeac ( ) {
  return tymeac_name;
} // end-method	
  
public String getUrl ( ) { 
  return tymeac_url_name; 
} // end-method	
  
public boolean  useAlt() { 
  return tymeac_use_alternate;
} // end-method	
  
public boolean  useIIOP() {
  return tymeac_use_iiop;
} // end-method	
  
public boolean  useRMI() { 
  return tymeac_use_rmi;
} // end-method	
  
} // end-class
