CONNECT 'jdbc:derby://localhost:1527/database/nflight;create=true;user=freelec;password=password1!';

/* Drop Tables */

DROP TABLE FREELEC.FLIGHT_AVAILABILITY;
DROP TABLE FREELEC.FLIGHT_SCHEDULE;
DROP TABLE FREELEC.AIRLINE;
DROP TABLE FREELEC.AIRPORT;

/* Create Tables */

CREATE TABLE FREELEC.AIRLINE
(
	AIRLINE_CODE CHAR(2) NOT NULL,
	AIRLINE_NAME VARCHAR(15) NOT NULL,
	LANGUAGE_CODE CHAR(2) NOT NULL,
	CONSTRAINT AIRLINE_PK_AIRLINE_CODE PRIMARY KEY (AIRLINE_CODE, LANGUAGE_CODE)
);

INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('7C', '제주항공', 'KR');
INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('7C', 'Jeju Air', 'EN');
INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('BX', '에어부산', 'KR');
INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('BX', 'Air Busan', 'EN');
INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('KE', '대한항공', 'KR');
INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('KE', 'Korea Air', 'EN');
INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('LJ', '진에어', 'KR');
INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('LJ', 'Jin Air', 'EN');
INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('OZ', '아시아나항공', 'KR');
INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('OZ', 'Asiana Airlines', 'EN');
INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('TW', '티웨이항공', 'KR');
INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('TW', 'Tway Airlines', 'EN');
INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('ZE', '이스타항공', 'KR');
INSERT INTO FREELEC.AIRLINE (AIRLINE_CODE, AIRLINE_NAME, LANGUAGE_CODE) VALUES ('ZE', 'Eastar Jet', 'EN');

SELECT * FROM FREELEC.AIRLINE;

commit; 

CREATE TABLE FREELEC.AIRPORT
(
	AIRPORT_CODE CHAR(3) NOT NULL,
	AIRPORT_NAME VARCHAR(25) NOT NULL,
	CITY_NAME VARCHAR(10) NOT NULL,
	COUNTRY_NAME VARCHAR(20) NOT NULL,
	COUNTRY_ISO_CODE CHAR(2) NOT NULL,
	CONSTRAINT AIRPORT_PK_AIRPORT_CODE PRIMARY KEY (AIRPORT_CODE)
);

CREATE TABLE FREELEC.FLIGHT_SCHEDULE
(
	FLIGHT_NO CHAR(6) NOT NULL,
	FLIGHT_SEGMENT VARCHAR(90) NOT NULL,
	FREQUENCY VARCHAR(8) DEFAULT 'N/A' NOT NULL,
	AIRLINE_CODE CHAR(2) NOT NULL,
	DEPARTURE_AIRPORT_CODE CHAR(3) NOT NULL,
	ARRIVAL_AIRPORT_CODE CHAR(3) NOT NULL,
	AIRCRAFT_MODEL VARCHAR(16) NOT NULL,
	ECONOMY_SEAT CHAR(10) NOT NULL,
	BUSINESS_SEAT CHAR(10) NOT NULL,
	FIRSTCLASS_SEAT CHAR(10) NOT NULL,
	EARN_MILES CHAR(10),
	OPERATION_START_DATE DATE NOT NULL,
	OPERATION_END_DATE DATE NOT NULL,
	DEPARTURE_TIME TIME NOT NULL,
	ARRIVAL_TIME TIME NOT NULL,
	CONSTRAINT FLIGHT_SCHEDULE_PK_FLIGHT_SEGMENT_FLIGHT_NO_FREQUENCY PRIMARY KEY (FLIGHT_NO, FLIGHT_SEGMENT, FREQUENCY)
);

ALTER TABLE FREELEC.FLIGHT_SCHEDULE
	ADD CONSTRAINT FLIGHT_SCHEDULE_FK_AIRLINE_CODE FOREIGN KEY (AIRLINE_CODE)
	REFERENCES FREELEC.AIRLINE (AIRLINE_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FREELEC.FLIGHT_SCHEDULE
	ADD CONSTRAINT FLIGHT_SCHEDULE_FK_DEPARTURE_AIRPORT_CODE FOREIGN KEY (DEPARTURE_AIRPORT_CODE)
	REFERENCES FREELEC.AIRPORT (AIRPORT_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE FREELEC.FLIGHT_SCHEDULE
	ADD CONSTRAINT FLIGHT_SCHEDULE_FK_ARRIVAL_AIRPORT_CODE FOREIGN KEY (ARRIVAL_AIRPORT_CODE)
	REFERENCES FREELEC.AIRPORT (AIRPORT_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

CREATE TABLE FREELEC.FLIGHT_AVAILABILITY
(
	FLIGHT_DATE DATE NOT NULL,
	FLIGHT_NO CHAR(6) NOT NULL,
	FLIGHT_SEGMENT VARCHAR(90) NOT NULL,
	FREQUENCY VARCHAR(8) DEFAULT 'N/A' NOT NULL,
	ECONOMY_SEAT_TAKEN CHAR(10) NOT NULL,
	BUSINESS_SEAT_TAKEN CHAR(10) NOT NULL,
	FIRSTCLASS_SEAT_TAKEN CHAR(10) NOT NULL,
	CONSTRAINT FLIGHT_AVAILABILITY_PK_FLIGHT_SEGMENT_FLIGHT_NO_FREQUENCY_FLIGHT_DATE PRIMARY KEY (FLIGHT_DATE, FLIGHT_NO, FLIGHT_SEGMENT, FREQUENCY)
);

ALTER TABLE FREELEC.FLIGHT_AVAILABILITY
	ADD FOREIGN KEY (FLIGHT_NO, FLIGHT_SEGMENT, FREQUENCY)
	REFERENCES FREELEC.FLIGHT_SCHEDULE (FLIGHT_NO, FLIGHT_SEGMENT, FREQUENCY)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

SHOW TABLES IN FREELEC;

DESCRIBE FREELEC.AIRPORT;

DESCRIBE FREELEC.AIRLINE;

DESCRIBE FREELEC.FLIGHT_SCHEDULE;

DESCRIBE FREELEC.FLIGHT_AVAILABILITY;

DISCONNECT;

EXIT;

