package com.tymeac.demo.jini2.client;

/* 
 * Copyright (c) 2002 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */
public class TyDemoJiniT1Bundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyDemoJiniT1_title", "Tymeac Jini Test 1"},
		{"DocText_text", ""},
		{"DocText_toolTipText", ""},
		{"ResultText_text", ""},
		{"ResultText_toolTipText", ""},
		{"DocLabel_text", "Doc Name"},
		{"DocLabel_toolTipText", ""},
		{"ResultLabel_text", "Result"},
		{"ResultLabel_toolTipText", ""},
		{"NoWaitButton_text", "Send, No Wait"},
		{"NoWaitButton_actionCommand", "Send, No Wait"},
		{"NoWaitButton_toolTipText", ""},
		{"WaitButton_text", "Send & Wait"},
		{"WaitButton_actionCommand", "Send & Wait"},
		{"WaitButton_toolTipText", ""},
		//}}End Automatic Code Generation Block
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
