package com.tymeac.serveruser;
// DO NOT EDIT THIS FILE
public class TymeacUserVariables {
  private String notify = null;
  private int sys_exit;
  private int mon_interval;
  private int inact_minutes;
  private String login_context = null;
  private boolean use_log = false;
  private String log_file = null;
  private String log_dir = null;
  private String alt_log_class = null;
  private boolean use_stats = false;
  private String stats_file = null;
  private String stats_dir = null;
  private String alt_stats_class = null;
  private String[] startup_classes = null;
  private String[] startup_functions = null; 
  private String[] shutdown_stage1_classes = null;
  private String[] shutdown_stage2_classes = null;
public TymeacUserVariables() {  
  notify = "TyNotify";  
  sys_exit = 1;
  mon_interval = 60;
  inact_minutes = 2;
  login_context = null;
  use_log = false;
  log_file = null;
  log_dir = null;
  alt_log_class = null;
  use_stats = false;
  stats_file = null;
  stats_dir = null;
  alt_stats_class = null;
  startup_classes = null;  
  startup_functions = null;  
  shutdown_stage1_classes = null;
  shutdown_stage2_classes = null;  
  
} // end-constructor
public int getInactivate() {
   return inact_minutes;
} // end-method
  
public String getLogAlt() {
  return alt_log_class;
} // end-method	
  
public String getLogDir() {
  return log_dir;
} // end-method	
  
public String getLogFile() {
  return log_file;
} // end-method	
  
public String getLoginContext() {
   return login_context;
} // end-method
  
public boolean getLogUse() {
  return use_log;
} // end-method	
  
public int getMonInterval() {
  return mon_interval;
} // end-method	
  
public String getNotify() {
  return notify;
} // end-method	
  
public String[] getShut1Classes() {
  return shutdown_stage1_classes;
} // end-method
  
public String[] getShut2Classes() {
  return shutdown_stage2_classes;
} // end-method
  
public String[] getStartUpClasses() {
  return startup_classes;
} // end-method	
  
public String[] getStartUpFunctions() {
  return startup_functions;
} // end-method	
  
public String getStatsAlt() {
  return alt_stats_class;
} // end-method	
  
public String getStatsDir() {
  return stats_dir;
} // end-method	
  
public String getStatsFile() {
  return stats_file;
} // end-method	
  
public boolean getStatsUse() {
  return use_stats;
} // end-method
  
public int getSysExit() {
  return sys_exit;
} // end-method
 
} // end-class
