package com.tymeac.serveruser;
// DO NOT EDIT THIS FILE
import java.util.*;
import com.tymeac.base.*;
public class TymeacUserQueues {
  protected int total_queues;
  protected TymeacIndividualQueue[] queues;
public TymeacUserQueues() {
  Vector<TymeacIndividualQueue> temp = new Vector<TymeacIndividualQueue>();
// [QUEUE]
temp.addElement( new TymeacIndividualQueue(	
"AAAA",
"com.tymeac.serveruser.Demo1",
"no",
"no",
0,
3,
10,
50,
30,
10,
20,
0.00F,
0.60F,
0.05F,
0.00F));
// [QUEUE]
temp.addElement( new TymeacIndividualQueue(	
"BBBB",
"com.tymeac.serveruser.Demo2",
"no",
"no",
0,
3,
10,
40,
30,
10,
20,
0.00F,
0.60F,
0.05F,
0.00F));
// [QUEUE]
temp.addElement( new TymeacIndividualQueue(	
"CCCC",
"com.tymeac.serveruser.Demo3",
"no",
"no",
0,
3,
10,
30,
30,
10,
20,
0.00F,
0.60F,
0.05F,
0.00F));
// [QUEUE]
temp.addElement( new TymeacIndividualQueue(	
"DDDD",
"com.tymeac.serveruser.DemoAgent1",
"yes",
"no",
0,
3,
10,
50,
30,
10,
20,
0.00F,
0.60F,
0.00F,
0.00F));
// [QUEUE]
temp.addElement( new TymeacIndividualQueue(	
"EEEE",
"com.tymeac.serveruser.DemoRecur",
"no",
"no",
0,
3,
10,
30,
30,
10,
20,
0.00F,
0.60F,
0.00F,
0.00F));
// [QUEUE]
temp.addElement( new TymeacIndividualQueue(	
"Notify",
"com.tymeac.serveruser.DemoNotify",
"no",
"no",
0,
1,
3,
30,
20,
10,
20,
0.00F,
0.00F,
0.00F,
0.00F));
// [QUEUE]
temp.addElement( new TymeacIndividualQueue(	
"Notify2",
"com.tymeac.serveruser.DemoNotify2",
"no",
"no",
0,
1,
3,
30,
20,
10,
20,
0.00F,
0.00F,
0.00F,
0.00F));
// [QUEUE]
temp.addElement( new TymeacIndividualQueue(	
"CancelQueue",
"com.tymeac.serveruser.DemoCancel",
"no",
"no",
0,
1,
1,
10,
10,
10,
20,
0.00F,
0.00F,
0.00F,
0.00F));
// [QUEUE]
temp.addElement( new TymeacIndividualQueue(	
"JQue1",
"com.tymeac.serveruser.JDemo1",
"no",
"no",
0,
3,
10,
30,
30,
10,
20,
0.00F,
0.60F,
0.00F,
0.00F));
// [QUEUE]
temp.addElement( new TymeacIndividualQueue(	
"JQue2",
"com.tymeac.serveruser.JDemo2",
"no",
"no",
0,
3,
10,
30,
30,
10,
20,
0.00F,
0.60F,
0.00F,
0.00F));
// [QUEUE]
temp.addElement( new TymeacIndividualQueue(	
"JQue3",
"com.tymeac.serveruser.JDemo3",
"no",
"no",
0,
3,
10,
30,
30,
10,
20,
0.00F,
0.60F,
0.00F,
0.00F));
// [QUEUE]
temp.addElement( new TymeacIndividualQueue(	
"JQue4",
"com.tymeac.serveruser.JDemo4",
"no",
"no",
0,
3,
10,
30,
30,
10,
20,
0.00F,
0.60F,
0.00F,
0.00F));
// [QUEUE]
temp.addElement( new TymeacIndividualQueue(	
"JQueAgent",
"com.tymeac.serveruser.JDemoAgent",
"yes",
"no",
0,
1,
10,
30,
30,
10,
20,
0.00F,
0.60F,
0.00F,
0.00F));
// [END]
  total_queues = temp.size(); 
  queues = new TymeacIndividualQueue[total_queues];
  for  (int i = 0; i < total_queues; i++) {
       queues[i] = temp.elementAt(i);
  } // end-for
} // end-constructor
public int getNbrQueues() {
  return total_queues;  
} // end-method
public TymeacIndividualQueue[] getQueues() {
  return queues;
} // end-method
} // end-class
