package com.tymeac.serveruser;
// DO NOT EDIT THIS FILE
import java.util.*;
import com.tymeac.base.*;
public class TymeacUserFunctions {
  protected int total_functions;
  protected TymeacIndividualFunction[] functions;
public TymeacUserFunctions() {
  Vector<TymeacIndividualFunction> temp = new Vector<TymeacIndividualFunction>();
  String[] list;
// [FUNCTION]
list = new String[3];
list[0] = "AAAA";
list[1] = "AAAA";
list[2] = "AAAA";
temp.addElement( new TymeacIndividualFunction(	
"Function_1",
"",
list));
// [FUNCTION]
list = new String[1];
list[0] = "AAAA";
temp.addElement( new TymeacIndividualFunction(	
"Function_2",
"",
list));
// [FUNCTION]
list = new String[2];
list[0] = "AAAA";
list[1] = "BBBB";
temp.addElement( new TymeacIndividualFunction(	
"Function_3",
"",
list));
// [FUNCTION]
list = new String[3];
list[0] = "AAAA";
list[1] = "BBBB";
list[2] = "CCCC";
temp.addElement( new TymeacIndividualFunction(	
"Function_4",
"",
list));
// [FUNCTION]
list = new String[1];
list[0] = "AAAA";
temp.addElement( new TymeacIndividualFunction(	
"Function_5",
"DDDD",
list));
// [FUNCTION]
list = new String[2];
list[0] = "AAAA";
list[1] = "BBBB";
temp.addElement( new TymeacIndividualFunction(	
"Function_6",
"DDDD",
list));
// [FUNCTION]
list = new String[3];
list[0] = "AAAA";
list[1] = "BBBB";
list[2] = "CCCC";
temp.addElement( new TymeacIndividualFunction(	
"Function_7",
"DDDD",
list));
// [FUNCTION]
list = new String[1];
list[0] = "EEEE";
temp.addElement( new TymeacIndividualFunction(	
"Function_8",
"",
list));
// [FUNCTION]
list = new String[1];
list[0] = "Notify";
temp.addElement( new TymeacIndividualFunction(	
"TyNotify",
"",
list));
// [FUNCTION]
list = new String[1];
list[0] = "Notify2";
temp.addElement( new TymeacIndividualFunction(  
"TyNotify2",
"",
list));
// [FUNCTION]
list = new String[1];
list[0] = "CancelQueue";
temp.addElement( new TymeacIndividualFunction(  
"CancelDemo",
"",
list));
// [FUNCTION]
list = new String[4];
list[0] = "JQue1";
list[1] = "JQue2";
list[2] = "JQue3";
list[3] = "JQue4";
temp.addElement( new TymeacIndividualFunction(	
"JFunction_1",
"JQueAgent",
list));
// [END]
  total_functions = temp.size(); 
  functions = new TymeacIndividualFunction[total_functions];
  for  (int i = 0; i < total_functions; i++) {
       functions[i] = temp.elementAt(i);
  } // end-for
} // end-constructor
public int getNbrFunctions() {
  return total_functions;  
} // end-method
public TymeacIndividualFunction[] getFunctions() {
  return functions;
} // end-method
} // end-class
