package com.tymeac.demo.jframe;

/* 
 * Copyright (c) 2002 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */

public class TyDemoInternalTestBundle3 extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyDemoInternalTest_title", "Tymeac Internal Sever Test"},
		{"Result_text", ""},
		{"Result_toolTipText", ""},
		{"ResultLabel_text", "Result:"},
		{"ResultLabel_toolTipText", ""},
		{"startButton_text", "Start Server"},
		{"startButton_actionCommand", "Start Server"},
		{"startButton_toolTipText", "Start the Internal Server test"},
		{"sendButton_text", "Start 22 Threads"},
		{"sendButton_actionCommand", "Start 22 Threads"},
		{"sendButton_toolTipText", ""},
		{"openButton_text", "Open Menu"},
		{"openButton_actionCommand", "Open Menu"},
		{"openButton_toolTipText", ""},
		{"closeButton_text", "Close Menu"},
		{"closeButton_actionCommand", "Close Menu"},
		{"closeButton_toolTipText", ""},
		{"stopButton_text", "Stop Server"},
		{"stopButton_actionCommand", "Stop Server"},
		{"stopButton_toolTipText", ""},
		//}}End Automatic Code Generation Block
		{"Result_text_1", "Start the server first"},
		{"Result_text_2", "Start the server first"},
		{"Result_text_3", "Start the server first"},
		{"Result_text_4", "Start the server first"},
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
