package com.tymeac.demo.jframe;

/* 
 * Copyright (c) 2002 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */
public class TyDemoT1Bundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyDemoT1_title", "Tymeac Single Test 1"},
		{"Function_text", ""},
		{"Function_toolTipText", "Between Function_1 - Function_8"},
		{"FunctionLabel_text", "Function Name"},
		{"FunctionLabel_toolTipText", ""},
		{"ALabel_text", "A:"},
		{"ALabel_toolTipText", ""},
		{"A1Text_text", ""},
		{"A1Text_toolTipText", "Two digits, 00 - 99"},
		{"A2Text_text", ""},
		{"A2Text_toolTipText", "Two digits, 00 - 99"},
		{"A3Text_text", ""},
		{"A3Text_toolTipText", "Two digits, 00 - 99"},
		{"BLabel_text", "B:"},
		{"BLabel_toolTipText", ""},
		{"B1Text_text", ""},
		{"B1Text_toolTipText", "Two digits, 00 - 99"},
		{"B2Text_text", ""},
		{"B2Text_toolTipText", "Two digits, 00 - 99"},
		{"B3Text_text", ""},
		{"B3Text_toolTipText", "Two digits, 00 - 99"},
		{"CLabel_text", "C:"},
		{"CLabel_toolTipText", ""},
		{"C1Text_text", ""},
		{"C1Text_toolTipText", "Two digits, 00 - 99"},
		{"C2Text_text", ""},
		{"C2Text_toolTipText", "Two digits, 00 - 99"},
		{"C3Text_text", ""},
		{"C3Text_toolTipText", "Two digits, 00 - 99"},
		{"Result_text", ""},
		{"Result_toolTipText", ""},
		{"ResultLabel_text", "Result:"},
		{"ResultLabel_toolTipText", ""},
		{"SendButton_text", "Send"},
		{"SendButton_actionCommand", "Send"},
		{"SendButton_toolTipText", ""},
		//}}End Automatic Code Generation Block
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
