package com.tymeac.demo.jframe;

/* 
 * Copyright (c) 2002 Cooperative Software Systems, Inc. 
 *
 * The contents of this file are subject to the Common Public License   
 * ("License"). You may not use this file except in compliance with
 * the License. A copy of the License is part of this distribution and
 * is also available at:
 * http://www.opensource.org/licenses/cpl.php
 */

/**
 * The resource bundle for the Strings associated with the class = Name minus "Bundle". This
 *   class was generated by VisualCafe.
 */
public class TyDemoT3Bundle extends java.util.ListResourceBundle
{
	static final Object[][] contents =
	{
		//Changing tags in the following block will
		//break the parsing of the related file
		//{{Start Automatic Code Generation Block
		{"TyDemoT3_title", "Tymeac Multi Thread Test"},
		{"StartText_text", ""},
		{"StartText_toolTipText", ""},
		{"StartLabel_text", "Number of Threads"},
		{"StartLabel_toolTipText", ""},
		{"StartButton_text", "Start"},
		{"StartButton_actionCommand", "Start"},
		{"StartButton_toolTipText", ""},
		{"StopButton_text", "Stop"},
		{"StopButton_actionCommand", "Stop"},
		{"StopButton_toolTipText", "Press to stop all processing"},
		{"RefreshButton_text", "Refresh"},
		{"RefreshButton_actionCommand", "Refresh"},
		{"RefreshButton_toolTipText", "Press to refresh list"},
		{"ListLabel_text", "  Status        RC      Times Used"},
		{"ListLabel_toolTipText", ""},
		{"ListScrollPane_toolTipText", ""},
		{"TheList_toolTipText", ""},
		//}}End Automatic Code Generation Block
	};
	public Object[][] getContents()
	{
		return contents;
	}
}
