// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.tymeac.jini.base;

public final class JiniActivationCreate2_Stub
    extends java.rmi.server.RemoteStub
    implements com.tymeac.jini.base.JiniFrontEndShutDown
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_shutDown_0;
    
    static {
	try {
	    $method_shutDown_0 = com.tymeac.jini.base.JiniFrontEndShutDown.class.getMethod("shutDown", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public JiniActivationCreate2_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of shutDown()
    public void shutDown()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_shutDown_0, null, 8641904352811051448L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
